// Code generated by ent, DO NOT EDIT.

package gatewaymodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gatewaymodel type in the database.
	Label = "gateway_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldOwnedBy holds the string denoting the owned_by field in the database.
	FieldOwnedBy = "owned_by"
	// FieldCreatedUnix holds the string denoting the created_unix field in the database.
	FieldCreatedUnix = "created_unix"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldContextWindowTokens holds the string denoting the context_window_tokens field in the database.
	FieldContextWindowTokens = "context_window_tokens"
	// FieldContextCompactTokens holds the string denoting the context_compact_tokens field in the database.
	FieldContextCompactTokens = "context_compact_tokens"
	// FieldContextHardTokens holds the string denoting the context_hard_tokens field in the database.
	FieldContextHardTokens = "context_hard_tokens"
	// FieldContextCompactBytes holds the string denoting the context_compact_bytes field in the database.
	FieldContextCompactBytes = "context_compact_bytes"
	// FieldContextHardBytes holds the string denoting the context_hard_bytes field in the database.
	FieldContextHardBytes = "context_hard_bytes"
	// FieldContextKeepItems holds the string denoting the context_keep_items field in the database.
	FieldContextKeepItems = "context_keep_items"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the gatewaymodel in the database.
	Table = "gateway_models"
)

// Columns holds all SQL columns for gatewaymodel fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldOwnedBy,
	FieldCreatedUnix,
	FieldEnabled,
	FieldSource,
	FieldContextWindowTokens,
	FieldContextCompactTokens,
	FieldContextHardTokens,
	FieldContextCompactBytes,
	FieldContextHardBytes,
	FieldContextKeepItems,
	FieldLastSeenAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// DefaultOwnedBy holds the default value on creation for the "owned_by" field.
	DefaultOwnedBy string
	// OwnedByValidator is a validator for the "owned_by" field. It is called by the builders before save.
	OwnedByValidator func(string) error
	// DefaultCreatedUnix holds the default value on creation for the "created_unix" field.
	DefaultCreatedUnix int64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultContextWindowTokens holds the default value on creation for the "context_window_tokens" field.
	DefaultContextWindowTokens int64
	// ContextWindowTokensValidator is a validator for the "context_window_tokens" field. It is called by the builders before save.
	ContextWindowTokensValidator func(int64) error
	// DefaultContextCompactTokens holds the default value on creation for the "context_compact_tokens" field.
	DefaultContextCompactTokens int64
	// ContextCompactTokensValidator is a validator for the "context_compact_tokens" field. It is called by the builders before save.
	ContextCompactTokensValidator func(int64) error
	// DefaultContextHardTokens holds the default value on creation for the "context_hard_tokens" field.
	DefaultContextHardTokens int64
	// ContextHardTokensValidator is a validator for the "context_hard_tokens" field. It is called by the builders before save.
	ContextHardTokensValidator func(int64) error
	// DefaultContextCompactBytes holds the default value on creation for the "context_compact_bytes" field.
	DefaultContextCompactBytes int64
	// ContextCompactBytesValidator is a validator for the "context_compact_bytes" field. It is called by the builders before save.
	ContextCompactBytesValidator func(int64) error
	// DefaultContextHardBytes holds the default value on creation for the "context_hard_bytes" field.
	DefaultContextHardBytes int64
	// ContextHardBytesValidator is a validator for the "context_hard_bytes" field. It is called by the builders before save.
	ContextHardBytesValidator func(int64) error
	// DefaultContextKeepItems holds the default value on creation for the "context_keep_items" field.
	DefaultContextKeepItems int
	// ContextKeepItemsValidator is a validator for the "context_keep_items" field. It is called by the builders before save.
	ContextKeepItemsValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GatewayModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByOwnedBy orders the results by the owned_by field.
func ByOwnedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnedBy, opts...).ToFunc()
}

// ByCreatedUnix orders the results by the created_unix field.
func ByCreatedUnix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedUnix, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByContextWindowTokens orders the results by the context_window_tokens field.
func ByContextWindowTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextWindowTokens, opts...).ToFunc()
}

// ByContextCompactTokens orders the results by the context_compact_tokens field.
func ByContextCompactTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextCompactTokens, opts...).ToFunc()
}

// ByContextHardTokens orders the results by the context_hard_tokens field.
func ByContextHardTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextHardTokens, opts...).ToFunc()
}

// ByContextCompactBytes orders the results by the context_compact_bytes field.
func ByContextCompactBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextCompactBytes, opts...).ToFunc()
}

// ByContextHardBytes orders the results by the context_hard_bytes field.
func ByContextHardBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextHardBytes, opts...).ToFunc()
}

// ByContextKeepItems orders the results by the context_keep_items field.
func ByContextKeepItems(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextKeepItems, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
