// Code generated by ent, DO NOT EDIT.

package gatewaymodel

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldID, id))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldModelID, v))
}

// OwnedBy applies equality check predicate on the "owned_by" field. It's identical to OwnedByEQ.
func OwnedBy(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldOwnedBy, v))
}

// CreatedUnix applies equality check predicate on the "created_unix" field. It's identical to CreatedUnixEQ.
func CreatedUnix(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldCreatedUnix, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldEnabled, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldSource, v))
}

// ContextWindowTokens applies equality check predicate on the "context_window_tokens" field. It's identical to ContextWindowTokensEQ.
func ContextWindowTokens(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextWindowTokens, v))
}

// ContextCompactTokens applies equality check predicate on the "context_compact_tokens" field. It's identical to ContextCompactTokensEQ.
func ContextCompactTokens(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextCompactTokens, v))
}

// ContextHardTokens applies equality check predicate on the "context_hard_tokens" field. It's identical to ContextHardTokensEQ.
func ContextHardTokens(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextHardTokens, v))
}

// ContextCompactBytes applies equality check predicate on the "context_compact_bytes" field. It's identical to ContextCompactBytesEQ.
func ContextCompactBytes(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextCompactBytes, v))
}

// ContextHardBytes applies equality check predicate on the "context_hard_bytes" field. It's identical to ContextHardBytesEQ.
func ContextHardBytes(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextHardBytes, v))
}

// ContextKeepItems applies equality check predicate on the "context_keep_items" field. It's identical to ContextKeepItemsEQ.
func ContextKeepItems(v int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextKeepItems, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldContainsFold(FieldModelID, v))
}

// OwnedByEQ applies the EQ predicate on the "owned_by" field.
func OwnedByEQ(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldOwnedBy, v))
}

// OwnedByNEQ applies the NEQ predicate on the "owned_by" field.
func OwnedByNEQ(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldOwnedBy, v))
}

// OwnedByIn applies the In predicate on the "owned_by" field.
func OwnedByIn(vs ...string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldOwnedBy, vs...))
}

// OwnedByNotIn applies the NotIn predicate on the "owned_by" field.
func OwnedByNotIn(vs ...string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldOwnedBy, vs...))
}

// OwnedByGT applies the GT predicate on the "owned_by" field.
func OwnedByGT(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldOwnedBy, v))
}

// OwnedByGTE applies the GTE predicate on the "owned_by" field.
func OwnedByGTE(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldOwnedBy, v))
}

// OwnedByLT applies the LT predicate on the "owned_by" field.
func OwnedByLT(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldOwnedBy, v))
}

// OwnedByLTE applies the LTE predicate on the "owned_by" field.
func OwnedByLTE(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldOwnedBy, v))
}

// OwnedByContains applies the Contains predicate on the "owned_by" field.
func OwnedByContains(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldContains(FieldOwnedBy, v))
}

// OwnedByHasPrefix applies the HasPrefix predicate on the "owned_by" field.
func OwnedByHasPrefix(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldHasPrefix(FieldOwnedBy, v))
}

// OwnedByHasSuffix applies the HasSuffix predicate on the "owned_by" field.
func OwnedByHasSuffix(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldHasSuffix(FieldOwnedBy, v))
}

// OwnedByEqualFold applies the EqualFold predicate on the "owned_by" field.
func OwnedByEqualFold(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEqualFold(FieldOwnedBy, v))
}

// OwnedByContainsFold applies the ContainsFold predicate on the "owned_by" field.
func OwnedByContainsFold(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldContainsFold(FieldOwnedBy, v))
}

// CreatedUnixEQ applies the EQ predicate on the "created_unix" field.
func CreatedUnixEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldCreatedUnix, v))
}

// CreatedUnixNEQ applies the NEQ predicate on the "created_unix" field.
func CreatedUnixNEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldCreatedUnix, v))
}

// CreatedUnixIn applies the In predicate on the "created_unix" field.
func CreatedUnixIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldCreatedUnix, vs...))
}

// CreatedUnixNotIn applies the NotIn predicate on the "created_unix" field.
func CreatedUnixNotIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldCreatedUnix, vs...))
}

// CreatedUnixGT applies the GT predicate on the "created_unix" field.
func CreatedUnixGT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldCreatedUnix, v))
}

// CreatedUnixGTE applies the GTE predicate on the "created_unix" field.
func CreatedUnixGTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldCreatedUnix, v))
}

// CreatedUnixLT applies the LT predicate on the "created_unix" field.
func CreatedUnixLT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldCreatedUnix, v))
}

// CreatedUnixLTE applies the LTE predicate on the "created_unix" field.
func CreatedUnixLTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldCreatedUnix, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldEnabled, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldContainsFold(FieldSource, v))
}

// ContextWindowTokensEQ applies the EQ predicate on the "context_window_tokens" field.
func ContextWindowTokensEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextWindowTokens, v))
}

// ContextWindowTokensNEQ applies the NEQ predicate on the "context_window_tokens" field.
func ContextWindowTokensNEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldContextWindowTokens, v))
}

// ContextWindowTokensIn applies the In predicate on the "context_window_tokens" field.
func ContextWindowTokensIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldContextWindowTokens, vs...))
}

// ContextWindowTokensNotIn applies the NotIn predicate on the "context_window_tokens" field.
func ContextWindowTokensNotIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldContextWindowTokens, vs...))
}

// ContextWindowTokensGT applies the GT predicate on the "context_window_tokens" field.
func ContextWindowTokensGT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldContextWindowTokens, v))
}

// ContextWindowTokensGTE applies the GTE predicate on the "context_window_tokens" field.
func ContextWindowTokensGTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldContextWindowTokens, v))
}

// ContextWindowTokensLT applies the LT predicate on the "context_window_tokens" field.
func ContextWindowTokensLT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldContextWindowTokens, v))
}

// ContextWindowTokensLTE applies the LTE predicate on the "context_window_tokens" field.
func ContextWindowTokensLTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldContextWindowTokens, v))
}

// ContextCompactTokensEQ applies the EQ predicate on the "context_compact_tokens" field.
func ContextCompactTokensEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextCompactTokens, v))
}

// ContextCompactTokensNEQ applies the NEQ predicate on the "context_compact_tokens" field.
func ContextCompactTokensNEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldContextCompactTokens, v))
}

// ContextCompactTokensIn applies the In predicate on the "context_compact_tokens" field.
func ContextCompactTokensIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldContextCompactTokens, vs...))
}

// ContextCompactTokensNotIn applies the NotIn predicate on the "context_compact_tokens" field.
func ContextCompactTokensNotIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldContextCompactTokens, vs...))
}

// ContextCompactTokensGT applies the GT predicate on the "context_compact_tokens" field.
func ContextCompactTokensGT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldContextCompactTokens, v))
}

// ContextCompactTokensGTE applies the GTE predicate on the "context_compact_tokens" field.
func ContextCompactTokensGTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldContextCompactTokens, v))
}

// ContextCompactTokensLT applies the LT predicate on the "context_compact_tokens" field.
func ContextCompactTokensLT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldContextCompactTokens, v))
}

// ContextCompactTokensLTE applies the LTE predicate on the "context_compact_tokens" field.
func ContextCompactTokensLTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldContextCompactTokens, v))
}

// ContextHardTokensEQ applies the EQ predicate on the "context_hard_tokens" field.
func ContextHardTokensEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextHardTokens, v))
}

// ContextHardTokensNEQ applies the NEQ predicate on the "context_hard_tokens" field.
func ContextHardTokensNEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldContextHardTokens, v))
}

// ContextHardTokensIn applies the In predicate on the "context_hard_tokens" field.
func ContextHardTokensIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldContextHardTokens, vs...))
}

// ContextHardTokensNotIn applies the NotIn predicate on the "context_hard_tokens" field.
func ContextHardTokensNotIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldContextHardTokens, vs...))
}

// ContextHardTokensGT applies the GT predicate on the "context_hard_tokens" field.
func ContextHardTokensGT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldContextHardTokens, v))
}

// ContextHardTokensGTE applies the GTE predicate on the "context_hard_tokens" field.
func ContextHardTokensGTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldContextHardTokens, v))
}

// ContextHardTokensLT applies the LT predicate on the "context_hard_tokens" field.
func ContextHardTokensLT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldContextHardTokens, v))
}

// ContextHardTokensLTE applies the LTE predicate on the "context_hard_tokens" field.
func ContextHardTokensLTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldContextHardTokens, v))
}

// ContextCompactBytesEQ applies the EQ predicate on the "context_compact_bytes" field.
func ContextCompactBytesEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextCompactBytes, v))
}

// ContextCompactBytesNEQ applies the NEQ predicate on the "context_compact_bytes" field.
func ContextCompactBytesNEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldContextCompactBytes, v))
}

// ContextCompactBytesIn applies the In predicate on the "context_compact_bytes" field.
func ContextCompactBytesIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldContextCompactBytes, vs...))
}

// ContextCompactBytesNotIn applies the NotIn predicate on the "context_compact_bytes" field.
func ContextCompactBytesNotIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldContextCompactBytes, vs...))
}

// ContextCompactBytesGT applies the GT predicate on the "context_compact_bytes" field.
func ContextCompactBytesGT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldContextCompactBytes, v))
}

// ContextCompactBytesGTE applies the GTE predicate on the "context_compact_bytes" field.
func ContextCompactBytesGTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldContextCompactBytes, v))
}

// ContextCompactBytesLT applies the LT predicate on the "context_compact_bytes" field.
func ContextCompactBytesLT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldContextCompactBytes, v))
}

// ContextCompactBytesLTE applies the LTE predicate on the "context_compact_bytes" field.
func ContextCompactBytesLTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldContextCompactBytes, v))
}

// ContextHardBytesEQ applies the EQ predicate on the "context_hard_bytes" field.
func ContextHardBytesEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextHardBytes, v))
}

// ContextHardBytesNEQ applies the NEQ predicate on the "context_hard_bytes" field.
func ContextHardBytesNEQ(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldContextHardBytes, v))
}

// ContextHardBytesIn applies the In predicate on the "context_hard_bytes" field.
func ContextHardBytesIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldContextHardBytes, vs...))
}

// ContextHardBytesNotIn applies the NotIn predicate on the "context_hard_bytes" field.
func ContextHardBytesNotIn(vs ...int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldContextHardBytes, vs...))
}

// ContextHardBytesGT applies the GT predicate on the "context_hard_bytes" field.
func ContextHardBytesGT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldContextHardBytes, v))
}

// ContextHardBytesGTE applies the GTE predicate on the "context_hard_bytes" field.
func ContextHardBytesGTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldContextHardBytes, v))
}

// ContextHardBytesLT applies the LT predicate on the "context_hard_bytes" field.
func ContextHardBytesLT(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldContextHardBytes, v))
}

// ContextHardBytesLTE applies the LTE predicate on the "context_hard_bytes" field.
func ContextHardBytesLTE(v int64) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldContextHardBytes, v))
}

// ContextKeepItemsEQ applies the EQ predicate on the "context_keep_items" field.
func ContextKeepItemsEQ(v int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldContextKeepItems, v))
}

// ContextKeepItemsNEQ applies the NEQ predicate on the "context_keep_items" field.
func ContextKeepItemsNEQ(v int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldContextKeepItems, v))
}

// ContextKeepItemsIn applies the In predicate on the "context_keep_items" field.
func ContextKeepItemsIn(vs ...int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldContextKeepItems, vs...))
}

// ContextKeepItemsNotIn applies the NotIn predicate on the "context_keep_items" field.
func ContextKeepItemsNotIn(vs ...int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldContextKeepItems, vs...))
}

// ContextKeepItemsGT applies the GT predicate on the "context_keep_items" field.
func ContextKeepItemsGT(v int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldContextKeepItems, v))
}

// ContextKeepItemsGTE applies the GTE predicate on the "context_keep_items" field.
func ContextKeepItemsGTE(v int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldContextKeepItems, v))
}

// ContextKeepItemsLT applies the LT predicate on the "context_keep_items" field.
func ContextKeepItemsLT(v int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldContextKeepItems, v))
}

// ContextKeepItemsLTE applies the LTE predicate on the "context_keep_items" field.
func ContextKeepItemsLTE(v int) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldContextKeepItems, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotNull(FieldLastSeenAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GatewayModel {
	return predicate.GatewayModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GatewayModel) predicate.GatewayModel {
	return predicate.GatewayModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GatewayModel) predicate.GatewayModel {
	return predicate.GatewayModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GatewayModel) predicate.GatewayModel {
	return predicate.GatewayModel(sql.NotPredicates(p))
}
