// Code generated by ent, DO NOT EDIT.

package gatewayalertrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gatewayalertrule type in the database.
	Label = "gateway_alert_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMetric holds the string denoting the metric field in the database.
	FieldMetric = "metric"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldThreshold holds the string denoting the threshold field in the database.
	FieldThreshold = "threshold"
	// FieldWindowSeconds holds the string denoting the window_seconds field in the database.
	FieldWindowSeconds = "window_seconds"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the gatewayalertrule in the database.
	Table = "gateway_alert_rules"
)

// Columns holds all SQL columns for gatewayalertrule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldMetric,
	FieldOperator,
	FieldThreshold,
	FieldWindowSeconds,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// MetricValidator is a validator for the "metric" field. It is called by the builders before save.
	MetricValidator func(string) error
	// DefaultOperator holds the default value on creation for the "operator" field.
	DefaultOperator string
	// OperatorValidator is a validator for the "operator" field. It is called by the builders before save.
	OperatorValidator func(string) error
	// DefaultThreshold holds the default value on creation for the "threshold" field.
	DefaultThreshold float64
	// DefaultWindowSeconds holds the default value on creation for the "window_seconds" field.
	DefaultWindowSeconds int64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GatewayAlertRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMetric orders the results by the metric field.
func ByMetric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetric, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByThreshold orders the results by the threshold field.
func ByThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThreshold, opts...).ToFunc()
}

// ByWindowSeconds orders the results by the window_seconds field.
func ByWindowSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowSeconds, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
