// Code generated by ent, DO NOT EDIT.

package gatewayusagelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gatewayusagelog type in the database.
	Label = "gateway_usage_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAPIKeyPrefix holds the string denoting the api_key_prefix field in the database.
	FieldAPIKeyPrefix = "api_key_prefix"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldCachedTokens holds the string denoting the cached_tokens field in the database.
	FieldCachedTokens = "cached_tokens"
	// FieldReasoningTokens holds the string denoting the reasoning_tokens field in the database.
	FieldReasoningTokens = "reasoning_tokens"
	// FieldRequestBytes holds the string denoting the request_bytes field in the database.
	FieldRequestBytes = "request_bytes"
	// FieldResponseBytes holds the string denoting the response_bytes field in the database.
	FieldResponseBytes = "response_bytes"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldErrorType holds the string denoting the error_type field in the database.
	FieldErrorType = "error_type"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the gatewayusagelog in the database.
	Table = "gateway_usage_logs"
)

// Columns holds all SQL columns for gatewayusagelog fields.
var Columns = []string{
	FieldID,
	FieldAPIKeyID,
	FieldAPIKeyPrefix,
	FieldRequestID,
	FieldMethod,
	FieldPath,
	FieldEndpoint,
	FieldModel,
	FieldStatusCode,
	FieldSuccess,
	FieldStream,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTotalTokens,
	FieldCachedTokens,
	FieldReasoningTokens,
	FieldRequestBytes,
	FieldResponseBytes,
	FieldDurationMs,
	FieldErrorType,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAPIKeyPrefix holds the default value on creation for the "api_key_prefix" field.
	DefaultAPIKeyPrefix string
	// APIKeyPrefixValidator is a validator for the "api_key_prefix" field. It is called by the builders before save.
	APIKeyPrefixValidator func(string) error
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultStatusCode holds the default value on creation for the "status_code" field.
	DefaultStatusCode int
	// DefaultSuccess holds the default value on creation for the "success" field.
	DefaultSuccess bool
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultCachedTokens holds the default value on creation for the "cached_tokens" field.
	DefaultCachedTokens int64
	// DefaultReasoningTokens holds the default value on creation for the "reasoning_tokens" field.
	DefaultReasoningTokens int64
	// DefaultRequestBytes holds the default value on creation for the "request_bytes" field.
	DefaultRequestBytes int64
	// DefaultResponseBytes holds the default value on creation for the "response_bytes" field.
	DefaultResponseBytes int64
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int64
	// DefaultErrorType holds the default value on creation for the "error_type" field.
	DefaultErrorType string
	// ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	ErrorTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the GatewayUsageLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAPIKeyPrefix orders the results by the api_key_prefix field.
func ByAPIKeyPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyPrefix, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByCachedTokens orders the results by the cached_tokens field.
func ByCachedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedTokens, opts...).ToFunc()
}

// ByReasoningTokens orders the results by the reasoning_tokens field.
func ByReasoningTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningTokens, opts...).ToFunc()
}

// ByRequestBytes orders the results by the request_bytes field.
func ByRequestBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBytes, opts...).ToFunc()
}

// ByResponseBytes orders the results by the response_bytes field.
func ByResponseBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBytes, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByErrorType orders the results by the error_type field.
func ByErrorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
