-- Modify "gateway_usage_logs" table
ALTER TABLE "gateway_usage_logs" ADD COLUMN "upstream_configured_mode" character varying NOT NULL DEFAULT '', ADD COLUMN "upstream_mode" character varying NOT NULL DEFAULT '', ADD COLUMN "upstream_fallback" boolean NOT NULL DEFAULT false, ADD COLUMN "upstream_error_type" character varying NOT NULL DEFAULT '';
-- Create index "gatewayusagelog_upstream_fallback_created_at" to table: "gateway_usage_logs"
CREATE INDEX "gatewayusagelog_upstream_fallback_created_at" ON "gateway_usage_logs" ("upstream_fallback", "created_at");
-- Create index "gatewayusagelog_upstream_mode_created_at" to table: "gateway_usage_logs"
CREATE INDEX "gatewayusagelog_upstream_mode_created_at" ON "gateway_usage_logs" ("upstream_mode", "created_at");
-- Create "gateway_settings" table
CREATE TABLE "gateway_settings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "key" character varying NOT NULL,
  "value" character varying NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewaysetting_key" to table: "gateway_settings"
CREATE UNIQUE INDEX "gatewaysetting_key" ON "gateway_settings" ("key");
