-- Modify "gateway_api_keys" table
ALTER TABLE "gateway_api_keys" ADD COLUMN "owner_user_id" bigint NULL;
-- Create index "gatewayapikey_owner_user_id" to table: "gateway_api_keys"
CREATE INDEX "gatewayapikey_owner_user_id" ON "gateway_api_keys" ("owner_user_id");
-- Create "gateway_alert_events" table
CREATE TABLE "gateway_alert_events" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "rule_id" bigint NULL,
  "rule_name" character varying NOT NULL DEFAULT '',
  "metric" character varying NOT NULL,
  "value" double precision NOT NULL DEFAULT 0,
  "threshold" double precision NOT NULL DEFAULT 0,
  "status" character varying NOT NULL DEFAULT 'open',
  "ack_by" bigint NULL,
  "ack_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewayalertevent_created_at" to table: "gateway_alert_events"
CREATE INDEX "gatewayalertevent_created_at" ON "gateway_alert_events" ("created_at");
-- Create index "gatewayalertevent_rule_id_created_at" to table: "gateway_alert_events"
CREATE INDEX "gatewayalertevent_rule_id_created_at" ON "gateway_alert_events" ("rule_id", "created_at");
-- Create index "gatewayalertevent_status_created_at" to table: "gateway_alert_events"
CREATE INDEX "gatewayalertevent_status_created_at" ON "gateway_alert_events" ("status", "created_at");
-- Create "gateway_alert_rules" table
CREATE TABLE "gateway_alert_rules" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "metric" character varying NOT NULL,
  "operator" character varying NOT NULL DEFAULT '>=',
  "threshold" double precision NOT NULL DEFAULT 0,
  "window_seconds" bigint NOT NULL DEFAULT 300,
  "enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewayalertrule_enabled" to table: "gateway_alert_rules"
CREATE INDEX "gatewayalertrule_enabled" ON "gateway_alert_rules" ("enabled");
-- Create index "gatewayalertrule_metric" to table: "gateway_alert_rules"
CREATE INDEX "gatewayalertrule_metric" ON "gateway_alert_rules" ("metric");
-- Create "gateway_audit_logs" table
CREATE TABLE "gateway_audit_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "actor_id" bigint NOT NULL DEFAULT 0,
  "actor_name" character varying NOT NULL DEFAULT '',
  "actor_role" character varying NOT NULL DEFAULT '',
  "action" character varying NOT NULL,
  "target_type" character varying NOT NULL DEFAULT '',
  "target_id" character varying NOT NULL DEFAULT '',
  "metadata" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewayauditlog_action_created_at" to table: "gateway_audit_logs"
CREATE INDEX "gatewayauditlog_action_created_at" ON "gateway_audit_logs" ("action", "created_at");
-- Create index "gatewayauditlog_actor_id_created_at" to table: "gateway_audit_logs"
CREATE INDEX "gatewayauditlog_actor_id_created_at" ON "gateway_audit_logs" ("actor_id", "created_at");
-- Create index "gatewayauditlog_created_at" to table: "gateway_audit_logs"
CREATE INDEX "gatewayauditlog_created_at" ON "gateway_audit_logs" ("created_at");
-- Create index "gatewayauditlog_target_type_target_id" to table: "gateway_audit_logs"
CREATE INDEX "gatewayauditlog_target_type_target_id" ON "gateway_audit_logs" ("target_type", "target_id");
-- Create "gateway_model_prices" table
CREATE TABLE "gateway_model_prices" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "model_id" character varying NOT NULL,
  "input_usd_per_million" double precision NOT NULL DEFAULT 0,
  "cached_input_usd_per_million" double precision NOT NULL DEFAULT 0,
  "output_usd_per_million" double precision NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewaymodelprice_model_id" to table: "gateway_model_prices"
CREATE UNIQUE INDEX "gatewaymodelprice_model_id" ON "gateway_model_prices" ("model_id");
-- Create "gateway_policies" table
CREATE TABLE "gateway_policies" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "api_key_id" bigint NOT NULL,
  "model_id" character varying NOT NULL,
  "rpm" bigint NOT NULL DEFAULT 0,
  "tpm" bigint NOT NULL DEFAULT 0,
  "daily_requests" bigint NOT NULL DEFAULT 0,
  "monthly_requests" bigint NOT NULL DEFAULT 0,
  "daily_tokens" bigint NOT NULL DEFAULT 0,
  "monthly_tokens" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewaypolicy_api_key_id_model_id" to table: "gateway_policies"
CREATE UNIQUE INDEX "gatewaypolicy_api_key_id_model_id" ON "gateway_policies" ("api_key_id", "model_id");
-- Create index "gatewaypolicy_model_id" to table: "gateway_policies"
CREATE INDEX "gatewaypolicy_model_id" ON "gateway_policies" ("model_id");
