-- Create "gateway_api_keys" table
CREATE TABLE "gateway_api_keys" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "key_hash" character varying NOT NULL,
  "key_prefix" character varying NOT NULL,
  "key_last4" character varying NOT NULL,
  "disabled" boolean NOT NULL DEFAULT false,
  "quota_requests" bigint NOT NULL DEFAULT 0,
  "quota_total_tokens" bigint NOT NULL DEFAULT 0,
  "allowed_models" jsonb NULL,
  "last_used_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewayapikey_disabled" to table: "gateway_api_keys"
CREATE INDEX "gatewayapikey_disabled" ON "gateway_api_keys" ("disabled");
-- Create index "gatewayapikey_key_hash" to table: "gateway_api_keys"
CREATE UNIQUE INDEX "gatewayapikey_key_hash" ON "gateway_api_keys" ("key_hash");
-- Create "gateway_models" table
CREATE TABLE "gateway_models" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "model_id" character varying NOT NULL,
  "owned_by" character varying NOT NULL DEFAULT '',
  "created_unix" bigint NOT NULL DEFAULT 0,
  "enabled" boolean NOT NULL DEFAULT true,
  "source" character varying NOT NULL DEFAULT 'manual',
  "last_seen_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewaymodel_enabled" to table: "gateway_models"
CREATE INDEX "gatewaymodel_enabled" ON "gateway_models" ("enabled");
-- Create index "gatewaymodel_model_id" to table: "gateway_models"
CREATE UNIQUE INDEX "gatewaymodel_model_id" ON "gateway_models" ("model_id");
-- Create index "gatewaymodel_source" to table: "gateway_models"
CREATE INDEX "gatewaymodel_source" ON "gateway_models" ("source");
-- Create "gateway_usage_logs" table
CREATE TABLE "gateway_usage_logs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "api_key_id" bigint NULL,
  "api_key_prefix" character varying NOT NULL DEFAULT '',
  "request_id" character varying NOT NULL DEFAULT '',
  "method" character varying NOT NULL,
  "path" character varying NOT NULL,
  "endpoint" character varying NOT NULL DEFAULT '',
  "model" character varying NOT NULL DEFAULT '',
  "status_code" bigint NOT NULL DEFAULT 0,
  "success" boolean NOT NULL DEFAULT false,
  "stream" boolean NOT NULL DEFAULT false,
  "input_tokens" bigint NOT NULL DEFAULT 0,
  "output_tokens" bigint NOT NULL DEFAULT 0,
  "total_tokens" bigint NOT NULL DEFAULT 0,
  "cached_tokens" bigint NOT NULL DEFAULT 0,
  "reasoning_tokens" bigint NOT NULL DEFAULT 0,
  "request_bytes" bigint NOT NULL DEFAULT 0,
  "response_bytes" bigint NOT NULL DEFAULT 0,
  "duration_ms" bigint NOT NULL DEFAULT 0,
  "error_type" character varying NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gatewayusagelog_api_key_id_created_at" to table: "gateway_usage_logs"
CREATE INDEX "gatewayusagelog_api_key_id_created_at" ON "gateway_usage_logs" ("api_key_id", "created_at");
-- Create index "gatewayusagelog_created_at" to table: "gateway_usage_logs"
CREATE INDEX "gatewayusagelog_created_at" ON "gateway_usage_logs" ("created_at");
-- Create index "gatewayusagelog_endpoint_created_at" to table: "gateway_usage_logs"
CREATE INDEX "gatewayusagelog_endpoint_created_at" ON "gateway_usage_logs" ("endpoint", "created_at");
-- Create index "gatewayusagelog_model_created_at" to table: "gateway_usage_logs"
CREATE INDEX "gatewayusagelog_model_created_at" ON "gateway_usage_logs" ("model", "created_at");
-- Create index "gatewayusagelog_success_created_at" to table: "gateway_usage_logs"
CREATE INDEX "gatewayusagelog_success_created_at" ON "gateway_usage_logs" ("success", "created_at");
