-- Create "gateway_context_summaries" table
CREATE TABLE "gateway_context_summaries" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "session_id" character varying NOT NULL,
  "api_key_id" bigint NULL,
  "api_key_prefix" character varying NOT NULL DEFAULT '',
  "summary" text NOT NULL DEFAULT '',
  "summary_tokens" bigint NOT NULL DEFAULT 0,
  "compaction_count" bigint NOT NULL DEFAULT 0,
  "last_request_id" character varying NOT NULL DEFAULT '',
  "last_reason" character varying NOT NULL DEFAULT '',
  "last_original_bytes" bigint NOT NULL DEFAULT 0,
  "last_compacted_bytes" bigint NOT NULL DEFAULT 0,
  "last_original_tokens" bigint NOT NULL DEFAULT 0,
  "last_compacted_tokens" bigint NOT NULL DEFAULT 0,
  "last_error" character varying NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "gateway_context_summaries_session_id_key" to table: "gateway_context_summaries"
CREATE UNIQUE INDEX "gateway_context_summaries_session_id_key" ON "gateway_context_summaries" ("session_id");
-- Create index "gatewaycontextsummary_api_key_id_updated_at" to table: "gateway_context_summaries"
CREATE INDEX "gatewaycontextsummary_api_key_id_updated_at" ON "gateway_context_summaries" ("api_key_id", "updated_at");
-- Create index "gatewaycontextsummary_updated_at" to table: "gateway_context_summaries"
CREATE INDEX "gatewaycontextsummary_updated_at" ON "gateway_context_summaries" ("updated_at");
