// Code generated by ent, DO NOT EDIT.

package gatewayapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gatewayapikey type in the database.
	Label = "gateway_api_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKeyHash holds the string denoting the key_hash field in the database.
	FieldKeyHash = "key_hash"
	// FieldPlainKey holds the string denoting the plain_key field in the database.
	FieldPlainKey = "plain_key"
	// FieldKeyPrefix holds the string denoting the key_prefix field in the database.
	FieldKeyPrefix = "key_prefix"
	// FieldKeyLast4 holds the string denoting the key_last4 field in the database.
	FieldKeyLast4 = "key_last4"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldQuotaRequests holds the string denoting the quota_requests field in the database.
	FieldQuotaRequests = "quota_requests"
	// FieldQuotaTotalTokens holds the string denoting the quota_total_tokens field in the database.
	FieldQuotaTotalTokens = "quota_total_tokens"
	// FieldQuotaDailyTokens holds the string denoting the quota_daily_tokens field in the database.
	FieldQuotaDailyTokens = "quota_daily_tokens"
	// FieldQuotaWeeklyTokens holds the string denoting the quota_weekly_tokens field in the database.
	FieldQuotaWeeklyTokens = "quota_weekly_tokens"
	// FieldQuotaDailyInputTokens holds the string denoting the quota_daily_input_tokens field in the database.
	FieldQuotaDailyInputTokens = "quota_daily_input_tokens"
	// FieldQuotaWeeklyInputTokens holds the string denoting the quota_weekly_input_tokens field in the database.
	FieldQuotaWeeklyInputTokens = "quota_weekly_input_tokens"
	// FieldQuotaDailyOutputTokens holds the string denoting the quota_daily_output_tokens field in the database.
	FieldQuotaDailyOutputTokens = "quota_daily_output_tokens"
	// FieldQuotaWeeklyOutputTokens holds the string denoting the quota_weekly_output_tokens field in the database.
	FieldQuotaWeeklyOutputTokens = "quota_weekly_output_tokens"
	// FieldQuotaDailyBillableInputTokens holds the string denoting the quota_daily_billable_input_tokens field in the database.
	FieldQuotaDailyBillableInputTokens = "quota_daily_billable_input_tokens"
	// FieldQuotaWeeklyBillableInputTokens holds the string denoting the quota_weekly_billable_input_tokens field in the database.
	FieldQuotaWeeklyBillableInputTokens = "quota_weekly_billable_input_tokens"
	// FieldAllowedModels holds the string denoting the allowed_models field in the database.
	FieldAllowedModels = "allowed_models"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the gatewayapikey in the database.
	Table = "gateway_api_keys"
)

// Columns holds all SQL columns for gatewayapikey fields.
var Columns = []string{
	FieldID,
	FieldOwnerUserID,
	FieldName,
	FieldKeyHash,
	FieldPlainKey,
	FieldKeyPrefix,
	FieldKeyLast4,
	FieldDisabled,
	FieldQuotaRequests,
	FieldQuotaTotalTokens,
	FieldQuotaDailyTokens,
	FieldQuotaWeeklyTokens,
	FieldQuotaDailyInputTokens,
	FieldQuotaWeeklyInputTokens,
	FieldQuotaDailyOutputTokens,
	FieldQuotaWeeklyOutputTokens,
	FieldQuotaDailyBillableInputTokens,
	FieldQuotaWeeklyBillableInputTokens,
	FieldAllowedModels,
	FieldLastUsedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	KeyHashValidator func(string) error
	// DefaultPlainKey holds the default value on creation for the "plain_key" field.
	DefaultPlainKey string
	// PlainKeyValidator is a validator for the "plain_key" field. It is called by the builders before save.
	PlainKeyValidator func(string) error
	// KeyPrefixValidator is a validator for the "key_prefix" field. It is called by the builders before save.
	KeyPrefixValidator func(string) error
	// KeyLast4Validator is a validator for the "key_last4" field. It is called by the builders before save.
	KeyLast4Validator func(string) error
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultQuotaRequests holds the default value on creation for the "quota_requests" field.
	DefaultQuotaRequests int64
	// DefaultQuotaTotalTokens holds the default value on creation for the "quota_total_tokens" field.
	DefaultQuotaTotalTokens int64
	// DefaultQuotaDailyTokens holds the default value on creation for the "quota_daily_tokens" field.
	DefaultQuotaDailyTokens int64
	// DefaultQuotaWeeklyTokens holds the default value on creation for the "quota_weekly_tokens" field.
	DefaultQuotaWeeklyTokens int64
	// DefaultQuotaDailyInputTokens holds the default value on creation for the "quota_daily_input_tokens" field.
	DefaultQuotaDailyInputTokens int64
	// DefaultQuotaWeeklyInputTokens holds the default value on creation for the "quota_weekly_input_tokens" field.
	DefaultQuotaWeeklyInputTokens int64
	// DefaultQuotaDailyOutputTokens holds the default value on creation for the "quota_daily_output_tokens" field.
	DefaultQuotaDailyOutputTokens int64
	// DefaultQuotaWeeklyOutputTokens holds the default value on creation for the "quota_weekly_output_tokens" field.
	DefaultQuotaWeeklyOutputTokens int64
	// DefaultQuotaDailyBillableInputTokens holds the default value on creation for the "quota_daily_billable_input_tokens" field.
	DefaultQuotaDailyBillableInputTokens int64
	// DefaultQuotaWeeklyBillableInputTokens holds the default value on creation for the "quota_weekly_billable_input_tokens" field.
	DefaultQuotaWeeklyBillableInputTokens int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GatewayAPIKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKeyHash orders the results by the key_hash field.
func ByKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyHash, opts...).ToFunc()
}

// ByPlainKey orders the results by the plain_key field.
func ByPlainKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlainKey, opts...).ToFunc()
}

// ByKeyPrefix orders the results by the key_prefix field.
func ByKeyPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyPrefix, opts...).ToFunc()
}

// ByKeyLast4 orders the results by the key_last4 field.
func ByKeyLast4(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyLast4, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// ByQuotaRequests orders the results by the quota_requests field.
func ByQuotaRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaRequests, opts...).ToFunc()
}

// ByQuotaTotalTokens orders the results by the quota_total_tokens field.
func ByQuotaTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaTotalTokens, opts...).ToFunc()
}

// ByQuotaDailyTokens orders the results by the quota_daily_tokens field.
func ByQuotaDailyTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaDailyTokens, opts...).ToFunc()
}

// ByQuotaWeeklyTokens orders the results by the quota_weekly_tokens field.
func ByQuotaWeeklyTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaWeeklyTokens, opts...).ToFunc()
}

// ByQuotaDailyInputTokens orders the results by the quota_daily_input_tokens field.
func ByQuotaDailyInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaDailyInputTokens, opts...).ToFunc()
}

// ByQuotaWeeklyInputTokens orders the results by the quota_weekly_input_tokens field.
func ByQuotaWeeklyInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaWeeklyInputTokens, opts...).ToFunc()
}

// ByQuotaDailyOutputTokens orders the results by the quota_daily_output_tokens field.
func ByQuotaDailyOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaDailyOutputTokens, opts...).ToFunc()
}

// ByQuotaWeeklyOutputTokens orders the results by the quota_weekly_output_tokens field.
func ByQuotaWeeklyOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaWeeklyOutputTokens, opts...).ToFunc()
}

// ByQuotaDailyBillableInputTokens orders the results by the quota_daily_billable_input_tokens field.
func ByQuotaDailyBillableInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaDailyBillableInputTokens, opts...).ToFunc()
}

// ByQuotaWeeklyBillableInputTokens orders the results by the quota_weekly_billable_input_tokens field.
func ByQuotaWeeklyBillableInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaWeeklyBillableInputTokens, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
