// Code generated by ent, DO NOT EDIT.

package gatewayapikey

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldID, id))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldOwnerUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldName, v))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldKeyHash, v))
}

// PlainKey applies equality check predicate on the "plain_key" field. It's identical to PlainKeyEQ.
func PlainKey(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldPlainKey, v))
}

// KeyPrefix applies equality check predicate on the "key_prefix" field. It's identical to KeyPrefixEQ.
func KeyPrefix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldKeyPrefix, v))
}

// KeyLast4 applies equality check predicate on the "key_last4" field. It's identical to KeyLast4EQ.
func KeyLast4(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldKeyLast4, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldDisabled, v))
}

// QuotaRequests applies equality check predicate on the "quota_requests" field. It's identical to QuotaRequestsEQ.
func QuotaRequests(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldQuotaRequests, v))
}

// QuotaTotalTokens applies equality check predicate on the "quota_total_tokens" field. It's identical to QuotaTotalTokensEQ.
func QuotaTotalTokens(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldQuotaTotalTokens, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldOwnerUserID, v))
}

// OwnerUserIDIsNil applies the IsNil predicate on the "owner_user_id" field.
func OwnerUserIDIsNil() predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIsNull(FieldOwnerUserID))
}

// OwnerUserIDNotNil applies the NotNil predicate on the "owner_user_id" field.
func OwnerUserIDNotNil() predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotNull(FieldOwnerUserID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContainsFold(FieldName, v))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldKeyHash, v))
}

// KeyHashContains applies the Contains predicate on the "key_hash" field.
func KeyHashContains(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContains(FieldKeyHash, v))
}

// KeyHashHasPrefix applies the HasPrefix predicate on the "key_hash" field.
func KeyHashHasPrefix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasPrefix(FieldKeyHash, v))
}

// KeyHashHasSuffix applies the HasSuffix predicate on the "key_hash" field.
func KeyHashHasSuffix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasSuffix(FieldKeyHash, v))
}

// KeyHashEqualFold applies the EqualFold predicate on the "key_hash" field.
func KeyHashEqualFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEqualFold(FieldKeyHash, v))
}

// KeyHashContainsFold applies the ContainsFold predicate on the "key_hash" field.
func KeyHashContainsFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContainsFold(FieldKeyHash, v))
}

// PlainKeyEQ applies the EQ predicate on the "plain_key" field.
func PlainKeyEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldPlainKey, v))
}

// PlainKeyNEQ applies the NEQ predicate on the "plain_key" field.
func PlainKeyNEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldPlainKey, v))
}

// PlainKeyIn applies the In predicate on the "plain_key" field.
func PlainKeyIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldPlainKey, vs...))
}

// PlainKeyNotIn applies the NotIn predicate on the "plain_key" field.
func PlainKeyNotIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldPlainKey, vs...))
}

// PlainKeyGT applies the GT predicate on the "plain_key" field.
func PlainKeyGT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldPlainKey, v))
}

// PlainKeyGTE applies the GTE predicate on the "plain_key" field.
func PlainKeyGTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldPlainKey, v))
}

// PlainKeyLT applies the LT predicate on the "plain_key" field.
func PlainKeyLT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldPlainKey, v))
}

// PlainKeyLTE applies the LTE predicate on the "plain_key" field.
func PlainKeyLTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldPlainKey, v))
}

// PlainKeyContains applies the Contains predicate on the "plain_key" field.
func PlainKeyContains(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContains(FieldPlainKey, v))
}

// PlainKeyHasPrefix applies the HasPrefix predicate on the "plain_key" field.
func PlainKeyHasPrefix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasPrefix(FieldPlainKey, v))
}

// PlainKeyHasSuffix applies the HasSuffix predicate on the "plain_key" field.
func PlainKeyHasSuffix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasSuffix(FieldPlainKey, v))
}

// PlainKeyEqualFold applies the EqualFold predicate on the "plain_key" field.
func PlainKeyEqualFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEqualFold(FieldPlainKey, v))
}

// PlainKeyContainsFold applies the ContainsFold predicate on the "plain_key" field.
func PlainKeyContainsFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContainsFold(FieldPlainKey, v))
}

// KeyPrefixEQ applies the EQ predicate on the "key_prefix" field.
func KeyPrefixEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldKeyPrefix, v))
}

// KeyPrefixNEQ applies the NEQ predicate on the "key_prefix" field.
func KeyPrefixNEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldKeyPrefix, v))
}

// KeyPrefixIn applies the In predicate on the "key_prefix" field.
func KeyPrefixIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldKeyPrefix, vs...))
}

// KeyPrefixNotIn applies the NotIn predicate on the "key_prefix" field.
func KeyPrefixNotIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldKeyPrefix, vs...))
}

// KeyPrefixGT applies the GT predicate on the "key_prefix" field.
func KeyPrefixGT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldKeyPrefix, v))
}

// KeyPrefixGTE applies the GTE predicate on the "key_prefix" field.
func KeyPrefixGTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldKeyPrefix, v))
}

// KeyPrefixLT applies the LT predicate on the "key_prefix" field.
func KeyPrefixLT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldKeyPrefix, v))
}

// KeyPrefixLTE applies the LTE predicate on the "key_prefix" field.
func KeyPrefixLTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldKeyPrefix, v))
}

// KeyPrefixContains applies the Contains predicate on the "key_prefix" field.
func KeyPrefixContains(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContains(FieldKeyPrefix, v))
}

// KeyPrefixHasPrefix applies the HasPrefix predicate on the "key_prefix" field.
func KeyPrefixHasPrefix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasPrefix(FieldKeyPrefix, v))
}

// KeyPrefixHasSuffix applies the HasSuffix predicate on the "key_prefix" field.
func KeyPrefixHasSuffix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasSuffix(FieldKeyPrefix, v))
}

// KeyPrefixEqualFold applies the EqualFold predicate on the "key_prefix" field.
func KeyPrefixEqualFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEqualFold(FieldKeyPrefix, v))
}

// KeyPrefixContainsFold applies the ContainsFold predicate on the "key_prefix" field.
func KeyPrefixContainsFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContainsFold(FieldKeyPrefix, v))
}

// KeyLast4EQ applies the EQ predicate on the "key_last4" field.
func KeyLast4EQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldKeyLast4, v))
}

// KeyLast4NEQ applies the NEQ predicate on the "key_last4" field.
func KeyLast4NEQ(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldKeyLast4, v))
}

// KeyLast4In applies the In predicate on the "key_last4" field.
func KeyLast4In(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldKeyLast4, vs...))
}

// KeyLast4NotIn applies the NotIn predicate on the "key_last4" field.
func KeyLast4NotIn(vs ...string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldKeyLast4, vs...))
}

// KeyLast4GT applies the GT predicate on the "key_last4" field.
func KeyLast4GT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldKeyLast4, v))
}

// KeyLast4GTE applies the GTE predicate on the "key_last4" field.
func KeyLast4GTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldKeyLast4, v))
}

// KeyLast4LT applies the LT predicate on the "key_last4" field.
func KeyLast4LT(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldKeyLast4, v))
}

// KeyLast4LTE applies the LTE predicate on the "key_last4" field.
func KeyLast4LTE(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldKeyLast4, v))
}

// KeyLast4Contains applies the Contains predicate on the "key_last4" field.
func KeyLast4Contains(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContains(FieldKeyLast4, v))
}

// KeyLast4HasPrefix applies the HasPrefix predicate on the "key_last4" field.
func KeyLast4HasPrefix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasPrefix(FieldKeyLast4, v))
}

// KeyLast4HasSuffix applies the HasSuffix predicate on the "key_last4" field.
func KeyLast4HasSuffix(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldHasSuffix(FieldKeyLast4, v))
}

// KeyLast4EqualFold applies the EqualFold predicate on the "key_last4" field.
func KeyLast4EqualFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEqualFold(FieldKeyLast4, v))
}

// KeyLast4ContainsFold applies the ContainsFold predicate on the "key_last4" field.
func KeyLast4ContainsFold(v string) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldContainsFold(FieldKeyLast4, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldDisabled, v))
}

// QuotaRequestsEQ applies the EQ predicate on the "quota_requests" field.
func QuotaRequestsEQ(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldQuotaRequests, v))
}

// QuotaRequestsNEQ applies the NEQ predicate on the "quota_requests" field.
func QuotaRequestsNEQ(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldQuotaRequests, v))
}

// QuotaRequestsIn applies the In predicate on the "quota_requests" field.
func QuotaRequestsIn(vs ...int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldQuotaRequests, vs...))
}

// QuotaRequestsNotIn applies the NotIn predicate on the "quota_requests" field.
func QuotaRequestsNotIn(vs ...int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldQuotaRequests, vs...))
}

// QuotaRequestsGT applies the GT predicate on the "quota_requests" field.
func QuotaRequestsGT(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldQuotaRequests, v))
}

// QuotaRequestsGTE applies the GTE predicate on the "quota_requests" field.
func QuotaRequestsGTE(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldQuotaRequests, v))
}

// QuotaRequestsLT applies the LT predicate on the "quota_requests" field.
func QuotaRequestsLT(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldQuotaRequests, v))
}

// QuotaRequestsLTE applies the LTE predicate on the "quota_requests" field.
func QuotaRequestsLTE(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldQuotaRequests, v))
}

// QuotaTotalTokensEQ applies the EQ predicate on the "quota_total_tokens" field.
func QuotaTotalTokensEQ(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldQuotaTotalTokens, v))
}

// QuotaTotalTokensNEQ applies the NEQ predicate on the "quota_total_tokens" field.
func QuotaTotalTokensNEQ(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldQuotaTotalTokens, v))
}

// QuotaTotalTokensIn applies the In predicate on the "quota_total_tokens" field.
func QuotaTotalTokensIn(vs ...int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldQuotaTotalTokens, vs...))
}

// QuotaTotalTokensNotIn applies the NotIn predicate on the "quota_total_tokens" field.
func QuotaTotalTokensNotIn(vs ...int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldQuotaTotalTokens, vs...))
}

// QuotaTotalTokensGT applies the GT predicate on the "quota_total_tokens" field.
func QuotaTotalTokensGT(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldQuotaTotalTokens, v))
}

// QuotaTotalTokensGTE applies the GTE predicate on the "quota_total_tokens" field.
func QuotaTotalTokensGTE(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldQuotaTotalTokens, v))
}

// QuotaTotalTokensLT applies the LT predicate on the "quota_total_tokens" field.
func QuotaTotalTokensLT(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldQuotaTotalTokens, v))
}

// QuotaTotalTokensLTE applies the LTE predicate on the "quota_total_tokens" field.
func QuotaTotalTokensLTE(v int64) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldQuotaTotalTokens, v))
}

// AllowedModelsIsNil applies the IsNil predicate on the "allowed_models" field.
func AllowedModelsIsNil() predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIsNull(FieldAllowedModels))
}

// AllowedModelsNotNil applies the NotNil predicate on the "allowed_models" field.
func AllowedModelsNotNil() predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotNull(FieldAllowedModels))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GatewayAPIKey) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GatewayAPIKey) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GatewayAPIKey) predicate.GatewayAPIKey {
	return predicate.GatewayAPIKey(sql.NotPredicates(p))
}
