// Code generated by ent, DO NOT EDIT.

package gatewaymodelprice

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gatewaymodelprice type in the database.
	Label = "gateway_model_price"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldInputUsdPerMillion holds the string denoting the input_usd_per_million field in the database.
	FieldInputUsdPerMillion = "input_usd_per_million"
	// FieldCachedInputUsdPerMillion holds the string denoting the cached_input_usd_per_million field in the database.
	FieldCachedInputUsdPerMillion = "cached_input_usd_per_million"
	// FieldOutputUsdPerMillion holds the string denoting the output_usd_per_million field in the database.
	FieldOutputUsdPerMillion = "output_usd_per_million"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the gatewaymodelprice in the database.
	Table = "gateway_model_prices"
)

// Columns holds all SQL columns for gatewaymodelprice fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldInputUsdPerMillion,
	FieldCachedInputUsdPerMillion,
	FieldOutputUsdPerMillion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// DefaultInputUsdPerMillion holds the default value on creation for the "input_usd_per_million" field.
	DefaultInputUsdPerMillion float64
	// DefaultCachedInputUsdPerMillion holds the default value on creation for the "cached_input_usd_per_million" field.
	DefaultCachedInputUsdPerMillion float64
	// DefaultOutputUsdPerMillion holds the default value on creation for the "output_usd_per_million" field.
	DefaultOutputUsdPerMillion float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GatewayModelPrice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByInputUsdPerMillion orders the results by the input_usd_per_million field.
func ByInputUsdPerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputUsdPerMillion, opts...).ToFunc()
}

// ByCachedInputUsdPerMillion orders the results by the cached_input_usd_per_million field.
func ByCachedInputUsdPerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedInputUsdPerMillion, opts...).ToFunc()
}

// ByOutputUsdPerMillion orders the results by the output_usd_per_million field.
func ByOutputUsdPerMillion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputUsdPerMillion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
