// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 64},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "oauth_provider", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "oauth_subject", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "oauth_email", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "oauth_display_name", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminuser_username",
				Unique:  true,
				Columns: []*schema.Column{AdminUsersColumns[1]},
			},
			{
				Name:    "adminuser_oauth_provider_oauth_subject",
				Unique:  true,
				Columns: []*schema.Column{AdminUsersColumns[3], AdminUsersColumns[4]},
			},
		},
	}
	// GatewayAPIKeysColumns holds the columns for the "gateway_api_keys" table.
	GatewayAPIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "owner_user_id", Type: field.TypeInt, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 80},
		{Name: "key_hash", Type: field.TypeString, Size: 64},
		{Name: "key_prefix", Type: field.TypeString, Size: 16},
		{Name: "key_last4", Type: field.TypeString, Size: 8},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "quota_requests", Type: field.TypeInt64, Default: 0},
		{Name: "quota_total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "allowed_models", Type: field.TypeJSON, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GatewayAPIKeysTable holds the schema information for the "gateway_api_keys" table.
	GatewayAPIKeysTable = &schema.Table{
		Name:       "gateway_api_keys",
		Columns:    GatewayAPIKeysColumns,
		PrimaryKey: []*schema.Column{GatewayAPIKeysColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewayapikey_owner_user_id",
				Unique:  false,
				Columns: []*schema.Column{GatewayAPIKeysColumns[1]},
			},
			{
				Name:    "gatewayapikey_key_hash",
				Unique:  true,
				Columns: []*schema.Column{GatewayAPIKeysColumns[3]},
			},
			{
				Name:    "gatewayapikey_disabled",
				Unique:  false,
				Columns: []*schema.Column{GatewayAPIKeysColumns[6]},
			},
		},
	}
	// GatewayAlertEventsColumns holds the columns for the "gateway_alert_events" table.
	GatewayAlertEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rule_id", Type: field.TypeInt, Nullable: true},
		{Name: "rule_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "metric", Type: field.TypeString, Size: 64},
		{Name: "value", Type: field.TypeFloat64, Default: 0},
		{Name: "threshold", Type: field.TypeFloat64, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 32, Default: "open"},
		{Name: "ack_by", Type: field.TypeInt, Nullable: true},
		{Name: "ack_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GatewayAlertEventsTable holds the schema information for the "gateway_alert_events" table.
	GatewayAlertEventsTable = &schema.Table{
		Name:       "gateway_alert_events",
		Columns:    GatewayAlertEventsColumns,
		PrimaryKey: []*schema.Column{GatewayAlertEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewayalertevent_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayAlertEventsColumns[9]},
			},
			{
				Name:    "gatewayalertevent_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayAlertEventsColumns[6], GatewayAlertEventsColumns[9]},
			},
			{
				Name:    "gatewayalertevent_rule_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayAlertEventsColumns[1], GatewayAlertEventsColumns[9]},
			},
		},
	}
	// GatewayAlertRulesColumns holds the columns for the "gateway_alert_rules" table.
	GatewayAlertRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "metric", Type: field.TypeString, Size: 64},
		{Name: "operator", Type: field.TypeString, Size: 8, Default: ">="},
		{Name: "threshold", Type: field.TypeFloat64, Default: 0},
		{Name: "window_seconds", Type: field.TypeInt64, Default: 300},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GatewayAlertRulesTable holds the schema information for the "gateway_alert_rules" table.
	GatewayAlertRulesTable = &schema.Table{
		Name:       "gateway_alert_rules",
		Columns:    GatewayAlertRulesColumns,
		PrimaryKey: []*schema.Column{GatewayAlertRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewayalertrule_enabled",
				Unique:  false,
				Columns: []*schema.Column{GatewayAlertRulesColumns[6]},
			},
			{
				Name:    "gatewayalertrule_metric",
				Unique:  false,
				Columns: []*schema.Column{GatewayAlertRulesColumns[2]},
			},
		},
	}
	// GatewayAuditLogsColumns holds the columns for the "gateway_audit_logs" table.
	GatewayAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "actor_id", Type: field.TypeInt, Default: 0},
		{Name: "actor_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "actor_role", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "action", Type: field.TypeString, Size: 128},
		{Name: "target_type", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "target_id", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GatewayAuditLogsTable holds the schema information for the "gateway_audit_logs" table.
	GatewayAuditLogsTable = &schema.Table{
		Name:       "gateway_audit_logs",
		Columns:    GatewayAuditLogsColumns,
		PrimaryKey: []*schema.Column{GatewayAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewayauditlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayAuditLogsColumns[8]},
			},
			{
				Name:    "gatewayauditlog_actor_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayAuditLogsColumns[1], GatewayAuditLogsColumns[8]},
			},
			{
				Name:    "gatewayauditlog_action_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayAuditLogsColumns[4], GatewayAuditLogsColumns[8]},
			},
			{
				Name:    "gatewayauditlog_target_type_target_id",
				Unique:  false,
				Columns: []*schema.Column{GatewayAuditLogsColumns[5], GatewayAuditLogsColumns[6]},
			},
		},
	}
	// GatewayModelsColumns holds the columns for the "gateway_models" table.
	GatewayModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model_id", Type: field.TypeString, Size: 128},
		{Name: "owned_by", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "created_unix", Type: field.TypeInt64, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "source", Type: field.TypeString, Size: 32, Default: "manual"},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GatewayModelsTable holds the schema information for the "gateway_models" table.
	GatewayModelsTable = &schema.Table{
		Name:       "gateway_models",
		Columns:    GatewayModelsColumns,
		PrimaryKey: []*schema.Column{GatewayModelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewaymodel_model_id",
				Unique:  true,
				Columns: []*schema.Column{GatewayModelsColumns[1]},
			},
			{
				Name:    "gatewaymodel_enabled",
				Unique:  false,
				Columns: []*schema.Column{GatewayModelsColumns[4]},
			},
			{
				Name:    "gatewaymodel_source",
				Unique:  false,
				Columns: []*schema.Column{GatewayModelsColumns[5]},
			},
		},
	}
	// GatewayModelPricesColumns holds the columns for the "gateway_model_prices" table.
	GatewayModelPricesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model_id", Type: field.TypeString, Size: 128},
		{Name: "input_usd_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "cached_input_usd_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "output_usd_per_million", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GatewayModelPricesTable holds the schema information for the "gateway_model_prices" table.
	GatewayModelPricesTable = &schema.Table{
		Name:       "gateway_model_prices",
		Columns:    GatewayModelPricesColumns,
		PrimaryKey: []*schema.Column{GatewayModelPricesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewaymodelprice_model_id",
				Unique:  true,
				Columns: []*schema.Column{GatewayModelPricesColumns[1]},
			},
		},
	}
	// GatewayPoliciesColumns holds the columns for the "gateway_policies" table.
	GatewayPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "api_key_id", Type: field.TypeInt},
		{Name: "model_id", Type: field.TypeString, Size: 128},
		{Name: "rpm", Type: field.TypeInt64, Default: 0},
		{Name: "tpm", Type: field.TypeInt64, Default: 0},
		{Name: "daily_requests", Type: field.TypeInt64, Default: 0},
		{Name: "monthly_requests", Type: field.TypeInt64, Default: 0},
		{Name: "daily_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "monthly_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GatewayPoliciesTable holds the schema information for the "gateway_policies" table.
	GatewayPoliciesTable = &schema.Table{
		Name:       "gateway_policies",
		Columns:    GatewayPoliciesColumns,
		PrimaryKey: []*schema.Column{GatewayPoliciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewaypolicy_api_key_id_model_id",
				Unique:  true,
				Columns: []*schema.Column{GatewayPoliciesColumns[1], GatewayPoliciesColumns[2]},
			},
			{
				Name:    "gatewaypolicy_model_id",
				Unique:  false,
				Columns: []*schema.Column{GatewayPoliciesColumns[2]},
			},
		},
	}
	// GatewayUsageLogsColumns holds the columns for the "gateway_usage_logs" table.
	GatewayUsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "api_key_prefix", Type: field.TypeString, Size: 16, Default: ""},
		{Name: "request_id", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "method", Type: field.TypeString, Size: 16},
		{Name: "path", Type: field.TypeString, Size: 256},
		{Name: "endpoint", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "model", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "status_code", Type: field.TypeInt, Default: 0},
		{Name: "success", Type: field.TypeBool, Default: false},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "input_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "cached_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "reasoning_tokens", Type: field.TypeInt64, Default: 0},
		{Name: "request_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "response_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "error_type", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GatewayUsageLogsTable holds the schema information for the "gateway_usage_logs" table.
	GatewayUsageLogsTable = &schema.Table{
		Name:       "gateway_usage_logs",
		Columns:    GatewayUsageLogsColumns,
		PrimaryKey: []*schema.Column{GatewayUsageLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gatewayusagelog_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayUsageLogsColumns[20]},
			},
			{
				Name:    "gatewayusagelog_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayUsageLogsColumns[1], GatewayUsageLogsColumns[20]},
			},
			{
				Name:    "gatewayusagelog_model_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayUsageLogsColumns[7], GatewayUsageLogsColumns[20]},
			},
			{
				Name:    "gatewayusagelog_endpoint_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayUsageLogsColumns[6], GatewayUsageLogsColumns[20]},
			},
			{
				Name:    "gatewayusagelog_success_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayUsageLogsColumns[9], GatewayUsageLogsColumns[20]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 32},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "oauth_provider", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "oauth_subject", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "oauth_email", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "oauth_display_name", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_oauth_provider_oauth_subject",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[3], UsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminUsersTable,
		GatewayAPIKeysTable,
		GatewayAlertEventsTable,
		GatewayAlertRulesTable,
		GatewayAuditLogsTable,
		GatewayModelsTable,
		GatewayModelPricesTable,
		GatewayPoliciesTable,
		GatewayUsageLogsTable,
		UsersTable,
	}
)

func init() {
}
