// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/internal/data/model/ent/gatewayalertrule"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayAlertRuleDelete is the builder for deleting a GatewayAlertRule entity.
type GatewayAlertRuleDelete struct {
	config
	hooks    []Hook
	mutation *GatewayAlertRuleMutation
}

// Where appends a list predicates to the GatewayAlertRuleDelete builder.
func (_d *GatewayAlertRuleDelete) Where(ps ...predicate.GatewayAlertRule) *GatewayAlertRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GatewayAlertRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayAlertRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GatewayAlertRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gatewayalertrule.Table, sqlgraph.NewFieldSpec(gatewayalertrule.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GatewayAlertRuleDeleteOne is the builder for deleting a single GatewayAlertRule entity.
type GatewayAlertRuleDeleteOne struct {
	_d *GatewayAlertRuleDelete
}

// Where appends a list predicates to the GatewayAlertRuleDelete builder.
func (_d *GatewayAlertRuleDeleteOne) Where(ps ...predicate.GatewayAlertRule) *GatewayAlertRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GatewayAlertRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gatewayalertrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayAlertRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
