// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewaymodelprice"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayModelPriceUpdate is the builder for updating GatewayModelPrice entities.
type GatewayModelPriceUpdate struct {
	config
	hooks    []Hook
	mutation *GatewayModelPriceMutation
}

// Where appends a list predicates to the GatewayModelPriceUpdate builder.
func (_u *GatewayModelPriceUpdate) Where(ps ...predicate.GatewayModelPrice) *GatewayModelPriceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *GatewayModelPriceUpdate) SetModelID(v string) *GatewayModelPriceUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *GatewayModelPriceUpdate) SetNillableModelID(v *string) *GatewayModelPriceUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetInputUsdPerMillion sets the "input_usd_per_million" field.
func (_u *GatewayModelPriceUpdate) SetInputUsdPerMillion(v float64) *GatewayModelPriceUpdate {
	_u.mutation.ResetInputUsdPerMillion()
	_u.mutation.SetInputUsdPerMillion(v)
	return _u
}

// SetNillableInputUsdPerMillion sets the "input_usd_per_million" field if the given value is not nil.
func (_u *GatewayModelPriceUpdate) SetNillableInputUsdPerMillion(v *float64) *GatewayModelPriceUpdate {
	if v != nil {
		_u.SetInputUsdPerMillion(*v)
	}
	return _u
}

// AddInputUsdPerMillion adds value to the "input_usd_per_million" field.
func (_u *GatewayModelPriceUpdate) AddInputUsdPerMillion(v float64) *GatewayModelPriceUpdate {
	_u.mutation.AddInputUsdPerMillion(v)
	return _u
}

// SetCachedInputUsdPerMillion sets the "cached_input_usd_per_million" field.
func (_u *GatewayModelPriceUpdate) SetCachedInputUsdPerMillion(v float64) *GatewayModelPriceUpdate {
	_u.mutation.ResetCachedInputUsdPerMillion()
	_u.mutation.SetCachedInputUsdPerMillion(v)
	return _u
}

// SetNillableCachedInputUsdPerMillion sets the "cached_input_usd_per_million" field if the given value is not nil.
func (_u *GatewayModelPriceUpdate) SetNillableCachedInputUsdPerMillion(v *float64) *GatewayModelPriceUpdate {
	if v != nil {
		_u.SetCachedInputUsdPerMillion(*v)
	}
	return _u
}

// AddCachedInputUsdPerMillion adds value to the "cached_input_usd_per_million" field.
func (_u *GatewayModelPriceUpdate) AddCachedInputUsdPerMillion(v float64) *GatewayModelPriceUpdate {
	_u.mutation.AddCachedInputUsdPerMillion(v)
	return _u
}

// SetOutputUsdPerMillion sets the "output_usd_per_million" field.
func (_u *GatewayModelPriceUpdate) SetOutputUsdPerMillion(v float64) *GatewayModelPriceUpdate {
	_u.mutation.ResetOutputUsdPerMillion()
	_u.mutation.SetOutputUsdPerMillion(v)
	return _u
}

// SetNillableOutputUsdPerMillion sets the "output_usd_per_million" field if the given value is not nil.
func (_u *GatewayModelPriceUpdate) SetNillableOutputUsdPerMillion(v *float64) *GatewayModelPriceUpdate {
	if v != nil {
		_u.SetOutputUsdPerMillion(*v)
	}
	return _u
}

// AddOutputUsdPerMillion adds value to the "output_usd_per_million" field.
func (_u *GatewayModelPriceUpdate) AddOutputUsdPerMillion(v float64) *GatewayModelPriceUpdate {
	_u.mutation.AddOutputUsdPerMillion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GatewayModelPriceUpdate) SetUpdatedAt(v time.Time) *GatewayModelPriceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GatewayModelPriceMutation object of the builder.
func (_u *GatewayModelPriceUpdate) Mutation() *GatewayModelPriceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GatewayModelPriceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayModelPriceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GatewayModelPriceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayModelPriceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GatewayModelPriceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gatewaymodelprice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GatewayModelPriceUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := gatewaymodelprice.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "GatewayModelPrice.model_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GatewayModelPriceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gatewaymodelprice.Table, gatewaymodelprice.Columns, sqlgraph.NewFieldSpec(gatewaymodelprice.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(gatewaymodelprice.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputUsdPerMillion(); ok {
		_spec.AddField(gatewaymodelprice.FieldInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CachedInputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldCachedInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCachedInputUsdPerMillion(); ok {
		_spec.AddField(gatewaymodelprice.FieldCachedInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldOutputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputUsdPerMillion(); ok {
		_spec.AddField(gatewaymodelprice.FieldOutputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaymodelprice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewaymodelprice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GatewayModelPriceUpdateOne is the builder for updating a single GatewayModelPrice entity.
type GatewayModelPriceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GatewayModelPriceMutation
}

// SetModelID sets the "model_id" field.
func (_u *GatewayModelPriceUpdateOne) SetModelID(v string) *GatewayModelPriceUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *GatewayModelPriceUpdateOne) SetNillableModelID(v *string) *GatewayModelPriceUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetInputUsdPerMillion sets the "input_usd_per_million" field.
func (_u *GatewayModelPriceUpdateOne) SetInputUsdPerMillion(v float64) *GatewayModelPriceUpdateOne {
	_u.mutation.ResetInputUsdPerMillion()
	_u.mutation.SetInputUsdPerMillion(v)
	return _u
}

// SetNillableInputUsdPerMillion sets the "input_usd_per_million" field if the given value is not nil.
func (_u *GatewayModelPriceUpdateOne) SetNillableInputUsdPerMillion(v *float64) *GatewayModelPriceUpdateOne {
	if v != nil {
		_u.SetInputUsdPerMillion(*v)
	}
	return _u
}

// AddInputUsdPerMillion adds value to the "input_usd_per_million" field.
func (_u *GatewayModelPriceUpdateOne) AddInputUsdPerMillion(v float64) *GatewayModelPriceUpdateOne {
	_u.mutation.AddInputUsdPerMillion(v)
	return _u
}

// SetCachedInputUsdPerMillion sets the "cached_input_usd_per_million" field.
func (_u *GatewayModelPriceUpdateOne) SetCachedInputUsdPerMillion(v float64) *GatewayModelPriceUpdateOne {
	_u.mutation.ResetCachedInputUsdPerMillion()
	_u.mutation.SetCachedInputUsdPerMillion(v)
	return _u
}

// SetNillableCachedInputUsdPerMillion sets the "cached_input_usd_per_million" field if the given value is not nil.
func (_u *GatewayModelPriceUpdateOne) SetNillableCachedInputUsdPerMillion(v *float64) *GatewayModelPriceUpdateOne {
	if v != nil {
		_u.SetCachedInputUsdPerMillion(*v)
	}
	return _u
}

// AddCachedInputUsdPerMillion adds value to the "cached_input_usd_per_million" field.
func (_u *GatewayModelPriceUpdateOne) AddCachedInputUsdPerMillion(v float64) *GatewayModelPriceUpdateOne {
	_u.mutation.AddCachedInputUsdPerMillion(v)
	return _u
}

// SetOutputUsdPerMillion sets the "output_usd_per_million" field.
func (_u *GatewayModelPriceUpdateOne) SetOutputUsdPerMillion(v float64) *GatewayModelPriceUpdateOne {
	_u.mutation.ResetOutputUsdPerMillion()
	_u.mutation.SetOutputUsdPerMillion(v)
	return _u
}

// SetNillableOutputUsdPerMillion sets the "output_usd_per_million" field if the given value is not nil.
func (_u *GatewayModelPriceUpdateOne) SetNillableOutputUsdPerMillion(v *float64) *GatewayModelPriceUpdateOne {
	if v != nil {
		_u.SetOutputUsdPerMillion(*v)
	}
	return _u
}

// AddOutputUsdPerMillion adds value to the "output_usd_per_million" field.
func (_u *GatewayModelPriceUpdateOne) AddOutputUsdPerMillion(v float64) *GatewayModelPriceUpdateOne {
	_u.mutation.AddOutputUsdPerMillion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GatewayModelPriceUpdateOne) SetUpdatedAt(v time.Time) *GatewayModelPriceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GatewayModelPriceMutation object of the builder.
func (_u *GatewayModelPriceUpdateOne) Mutation() *GatewayModelPriceMutation {
	return _u.mutation
}

// Where appends a list predicates to the GatewayModelPriceUpdate builder.
func (_u *GatewayModelPriceUpdateOne) Where(ps ...predicate.GatewayModelPrice) *GatewayModelPriceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GatewayModelPriceUpdateOne) Select(field string, fields ...string) *GatewayModelPriceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GatewayModelPrice entity.
func (_u *GatewayModelPriceUpdateOne) Save(ctx context.Context) (*GatewayModelPrice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayModelPriceUpdateOne) SaveX(ctx context.Context) *GatewayModelPrice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GatewayModelPriceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayModelPriceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GatewayModelPriceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gatewaymodelprice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GatewayModelPriceUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := gatewaymodelprice.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "GatewayModelPrice.model_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GatewayModelPriceUpdateOne) sqlSave(ctx context.Context) (_node *GatewayModelPrice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gatewaymodelprice.Table, gatewaymodelprice.Columns, sqlgraph.NewFieldSpec(gatewaymodelprice.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GatewayModelPrice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gatewaymodelprice.FieldID)
		for _, f := range fields {
			if !gatewaymodelprice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gatewaymodelprice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(gatewaymodelprice.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputUsdPerMillion(); ok {
		_spec.AddField(gatewaymodelprice.FieldInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CachedInputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldCachedInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCachedInputUsdPerMillion(); ok {
		_spec.AddField(gatewaymodelprice.FieldCachedInputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldOutputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputUsdPerMillion(); ok {
		_spec.AddField(gatewaymodelprice.FieldOutputUsdPerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaymodelprice.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GatewayModelPrice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewaymodelprice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
