// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewaymodelprice"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayModelPriceCreate is the builder for creating a GatewayModelPrice entity.
type GatewayModelPriceCreate struct {
	config
	mutation *GatewayModelPriceMutation
	hooks    []Hook
}

// SetModelID sets the "model_id" field.
func (_c *GatewayModelPriceCreate) SetModelID(v string) *GatewayModelPriceCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetInputUsdPerMillion sets the "input_usd_per_million" field.
func (_c *GatewayModelPriceCreate) SetInputUsdPerMillion(v float64) *GatewayModelPriceCreate {
	_c.mutation.SetInputUsdPerMillion(v)
	return _c
}

// SetNillableInputUsdPerMillion sets the "input_usd_per_million" field if the given value is not nil.
func (_c *GatewayModelPriceCreate) SetNillableInputUsdPerMillion(v *float64) *GatewayModelPriceCreate {
	if v != nil {
		_c.SetInputUsdPerMillion(*v)
	}
	return _c
}

// SetCachedInputUsdPerMillion sets the "cached_input_usd_per_million" field.
func (_c *GatewayModelPriceCreate) SetCachedInputUsdPerMillion(v float64) *GatewayModelPriceCreate {
	_c.mutation.SetCachedInputUsdPerMillion(v)
	return _c
}

// SetNillableCachedInputUsdPerMillion sets the "cached_input_usd_per_million" field if the given value is not nil.
func (_c *GatewayModelPriceCreate) SetNillableCachedInputUsdPerMillion(v *float64) *GatewayModelPriceCreate {
	if v != nil {
		_c.SetCachedInputUsdPerMillion(*v)
	}
	return _c
}

// SetOutputUsdPerMillion sets the "output_usd_per_million" field.
func (_c *GatewayModelPriceCreate) SetOutputUsdPerMillion(v float64) *GatewayModelPriceCreate {
	_c.mutation.SetOutputUsdPerMillion(v)
	return _c
}

// SetNillableOutputUsdPerMillion sets the "output_usd_per_million" field if the given value is not nil.
func (_c *GatewayModelPriceCreate) SetNillableOutputUsdPerMillion(v *float64) *GatewayModelPriceCreate {
	if v != nil {
		_c.SetOutputUsdPerMillion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GatewayModelPriceCreate) SetCreatedAt(v time.Time) *GatewayModelPriceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GatewayModelPriceCreate) SetNillableCreatedAt(v *time.Time) *GatewayModelPriceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GatewayModelPriceCreate) SetUpdatedAt(v time.Time) *GatewayModelPriceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GatewayModelPriceCreate) SetNillableUpdatedAt(v *time.Time) *GatewayModelPriceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GatewayModelPriceMutation object of the builder.
func (_c *GatewayModelPriceCreate) Mutation() *GatewayModelPriceMutation {
	return _c.mutation
}

// Save creates the GatewayModelPrice in the database.
func (_c *GatewayModelPriceCreate) Save(ctx context.Context) (*GatewayModelPrice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GatewayModelPriceCreate) SaveX(ctx context.Context) *GatewayModelPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayModelPriceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayModelPriceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GatewayModelPriceCreate) defaults() {
	if _, ok := _c.mutation.InputUsdPerMillion(); !ok {
		v := gatewaymodelprice.DefaultInputUsdPerMillion
		_c.mutation.SetInputUsdPerMillion(v)
	}
	if _, ok := _c.mutation.CachedInputUsdPerMillion(); !ok {
		v := gatewaymodelprice.DefaultCachedInputUsdPerMillion
		_c.mutation.SetCachedInputUsdPerMillion(v)
	}
	if _, ok := _c.mutation.OutputUsdPerMillion(); !ok {
		v := gatewaymodelprice.DefaultOutputUsdPerMillion
		_c.mutation.SetOutputUsdPerMillion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gatewaymodelprice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gatewaymodelprice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GatewayModelPriceCreate) check() error {
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "GatewayModelPrice.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := gatewaymodelprice.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "GatewayModelPrice.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputUsdPerMillion(); !ok {
		return &ValidationError{Name: "input_usd_per_million", err: errors.New(`ent: missing required field "GatewayModelPrice.input_usd_per_million"`)}
	}
	if _, ok := _c.mutation.CachedInputUsdPerMillion(); !ok {
		return &ValidationError{Name: "cached_input_usd_per_million", err: errors.New(`ent: missing required field "GatewayModelPrice.cached_input_usd_per_million"`)}
	}
	if _, ok := _c.mutation.OutputUsdPerMillion(); !ok {
		return &ValidationError{Name: "output_usd_per_million", err: errors.New(`ent: missing required field "GatewayModelPrice.output_usd_per_million"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GatewayModelPrice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GatewayModelPrice.updated_at"`)}
	}
	return nil
}

func (_c *GatewayModelPriceCreate) sqlSave(ctx context.Context) (*GatewayModelPrice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GatewayModelPriceCreate) createSpec() (*GatewayModelPrice, *sqlgraph.CreateSpec) {
	var (
		_node = &GatewayModelPrice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gatewaymodelprice.Table, sqlgraph.NewFieldSpec(gatewaymodelprice.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(gatewaymodelprice.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.InputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldInputUsdPerMillion, field.TypeFloat64, value)
		_node.InputUsdPerMillion = value
	}
	if value, ok := _c.mutation.CachedInputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldCachedInputUsdPerMillion, field.TypeFloat64, value)
		_node.CachedInputUsdPerMillion = value
	}
	if value, ok := _c.mutation.OutputUsdPerMillion(); ok {
		_spec.SetField(gatewaymodelprice.FieldOutputUsdPerMillion, field.TypeFloat64, value)
		_node.OutputUsdPerMillion = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gatewaymodelprice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaymodelprice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GatewayModelPriceCreateBulk is the builder for creating many GatewayModelPrice entities in bulk.
type GatewayModelPriceCreateBulk struct {
	config
	err      error
	builders []*GatewayModelPriceCreate
}

// Save creates the GatewayModelPrice entities in the database.
func (_c *GatewayModelPriceCreateBulk) Save(ctx context.Context) ([]*GatewayModelPrice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GatewayModelPrice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GatewayModelPriceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GatewayModelPriceCreateBulk) SaveX(ctx context.Context) []*GatewayModelPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayModelPriceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayModelPriceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
