// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/gatewaycontextsummary"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GatewayContextSummary is the model entity for the GatewayContextSummary schema.
type GatewayContextSummary struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int `json:"api_key_id,omitempty"`
	// APIKeyPrefix holds the value of the "api_key_prefix" field.
	APIKeyPrefix string `json:"api_key_prefix,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// SummaryTokens holds the value of the "summary_tokens" field.
	SummaryTokens int64 `json:"summary_tokens,omitempty"`
	// CompactionCount holds the value of the "compaction_count" field.
	CompactionCount int `json:"compaction_count,omitempty"`
	// LastRequestID holds the value of the "last_request_id" field.
	LastRequestID string `json:"last_request_id,omitempty"`
	// LastReason holds the value of the "last_reason" field.
	LastReason string `json:"last_reason,omitempty"`
	// LastOriginalBytes holds the value of the "last_original_bytes" field.
	LastOriginalBytes int64 `json:"last_original_bytes,omitempty"`
	// LastCompactedBytes holds the value of the "last_compacted_bytes" field.
	LastCompactedBytes int64 `json:"last_compacted_bytes,omitempty"`
	// LastOriginalTokens holds the value of the "last_original_tokens" field.
	LastOriginalTokens int64 `json:"last_original_tokens,omitempty"`
	// LastCompactedTokens holds the value of the "last_compacted_tokens" field.
	LastCompactedTokens int64 `json:"last_compacted_tokens,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GatewayContextSummary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gatewaycontextsummary.FieldID, gatewaycontextsummary.FieldAPIKeyID, gatewaycontextsummary.FieldSummaryTokens, gatewaycontextsummary.FieldCompactionCount, gatewaycontextsummary.FieldLastOriginalBytes, gatewaycontextsummary.FieldLastCompactedBytes, gatewaycontextsummary.FieldLastOriginalTokens, gatewaycontextsummary.FieldLastCompactedTokens:
			values[i] = new(sql.NullInt64)
		case gatewaycontextsummary.FieldSessionID, gatewaycontextsummary.FieldAPIKeyPrefix, gatewaycontextsummary.FieldSummary, gatewaycontextsummary.FieldLastRequestID, gatewaycontextsummary.FieldLastReason, gatewaycontextsummary.FieldLastError:
			values[i] = new(sql.NullString)
		case gatewaycontextsummary.FieldCreatedAt, gatewaycontextsummary.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GatewayContextSummary fields.
func (_m *GatewayContextSummary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gatewaycontextsummary.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gatewaycontextsummary.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case gatewaycontextsummary.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int)
				*_m.APIKeyID = int(value.Int64)
			}
		case gatewaycontextsummary.FieldAPIKeyPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_prefix", values[i])
			} else if value.Valid {
				_m.APIKeyPrefix = value.String
			}
		case gatewaycontextsummary.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case gatewaycontextsummary.FieldSummaryTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field summary_tokens", values[i])
			} else if value.Valid {
				_m.SummaryTokens = value.Int64
			}
		case gatewaycontextsummary.FieldCompactionCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field compaction_count", values[i])
			} else if value.Valid {
				_m.CompactionCount = int(value.Int64)
			}
		case gatewaycontextsummary.FieldLastRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_request_id", values[i])
			} else if value.Valid {
				_m.LastRequestID = value.String
			}
		case gatewaycontextsummary.FieldLastReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_reason", values[i])
			} else if value.Valid {
				_m.LastReason = value.String
			}
		case gatewaycontextsummary.FieldLastOriginalBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_original_bytes", values[i])
			} else if value.Valid {
				_m.LastOriginalBytes = value.Int64
			}
		case gatewaycontextsummary.FieldLastCompactedBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_compacted_bytes", values[i])
			} else if value.Valid {
				_m.LastCompactedBytes = value.Int64
			}
		case gatewaycontextsummary.FieldLastOriginalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_original_tokens", values[i])
			} else if value.Valid {
				_m.LastOriginalTokens = value.Int64
			}
		case gatewaycontextsummary.FieldLastCompactedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_compacted_tokens", values[i])
			} else if value.Valid {
				_m.LastCompactedTokens = value.Int64
			}
		case gatewaycontextsummary.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case gatewaycontextsummary.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gatewaycontextsummary.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GatewayContextSummary.
// This includes values selected through modifiers, order, etc.
func (_m *GatewayContextSummary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GatewayContextSummary.
// Note that you need to call GatewayContextSummary.Unwrap() before calling this method if this GatewayContextSummary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GatewayContextSummary) Update() *GatewayContextSummaryUpdateOne {
	return NewGatewayContextSummaryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GatewayContextSummary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GatewayContextSummary) Unwrap() *GatewayContextSummary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GatewayContextSummary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GatewayContextSummary) String() string {
	var builder strings.Builder
	builder.WriteString("GatewayContextSummary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("api_key_prefix=")
	builder.WriteString(_m.APIKeyPrefix)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("summary_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.SummaryTokens))
	builder.WriteString(", ")
	builder.WriteString("compaction_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompactionCount))
	builder.WriteString(", ")
	builder.WriteString("last_request_id=")
	builder.WriteString(_m.LastRequestID)
	builder.WriteString(", ")
	builder.WriteString("last_reason=")
	builder.WriteString(_m.LastReason)
	builder.WriteString(", ")
	builder.WriteString("last_original_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastOriginalBytes))
	builder.WriteString(", ")
	builder.WriteString("last_compacted_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastCompactedBytes))
	builder.WriteString(", ")
	builder.WriteString("last_original_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastOriginalTokens))
	builder.WriteString(", ")
	builder.WriteString("last_compacted_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastCompactedTokens))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GatewayContextSummaries is a parsable slice of GatewayContextSummary.
type GatewayContextSummaries []*GatewayContextSummary
