// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/internal/data/model/ent/gatewayauditlog"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayAuditLogDelete is the builder for deleting a GatewayAuditLog entity.
type GatewayAuditLogDelete struct {
	config
	hooks    []Hook
	mutation *GatewayAuditLogMutation
}

// Where appends a list predicates to the GatewayAuditLogDelete builder.
func (_d *GatewayAuditLogDelete) Where(ps ...predicate.GatewayAuditLog) *GatewayAuditLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GatewayAuditLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayAuditLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GatewayAuditLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gatewayauditlog.Table, sqlgraph.NewFieldSpec(gatewayauditlog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GatewayAuditLogDeleteOne is the builder for deleting a single GatewayAuditLog entity.
type GatewayAuditLogDeleteOne struct {
	_d *GatewayAuditLogDelete
}

// Where appends a list predicates to the GatewayAuditLogDelete builder.
func (_d *GatewayAuditLogDeleteOne) Where(ps ...predicate.GatewayAuditLog) *GatewayAuditLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GatewayAuditLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gatewayauditlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayAuditLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
