// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/gatewayalertrule"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GatewayAlertRule is the model entity for the GatewayAlertRule schema.
type GatewayAlertRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Metric holds the value of the "metric" field.
	Metric string `json:"metric,omitempty"`
	// Operator holds the value of the "operator" field.
	Operator string `json:"operator,omitempty"`
	// Threshold holds the value of the "threshold" field.
	Threshold float64 `json:"threshold,omitempty"`
	// WindowSeconds holds the value of the "window_seconds" field.
	WindowSeconds int64 `json:"window_seconds,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GatewayAlertRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gatewayalertrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case gatewayalertrule.FieldThreshold:
			values[i] = new(sql.NullFloat64)
		case gatewayalertrule.FieldID, gatewayalertrule.FieldWindowSeconds:
			values[i] = new(sql.NullInt64)
		case gatewayalertrule.FieldName, gatewayalertrule.FieldMetric, gatewayalertrule.FieldOperator:
			values[i] = new(sql.NullString)
		case gatewayalertrule.FieldCreatedAt, gatewayalertrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GatewayAlertRule fields.
func (_m *GatewayAlertRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gatewayalertrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gatewayalertrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case gatewayalertrule.FieldMetric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metric", values[i])
			} else if value.Valid {
				_m.Metric = value.String
			}
		case gatewayalertrule.FieldOperator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator", values[i])
			} else if value.Valid {
				_m.Operator = value.String
			}
		case gatewayalertrule.FieldThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field threshold", values[i])
			} else if value.Valid {
				_m.Threshold = value.Float64
			}
		case gatewayalertrule.FieldWindowSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field window_seconds", values[i])
			} else if value.Valid {
				_m.WindowSeconds = value.Int64
			}
		case gatewayalertrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case gatewayalertrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gatewayalertrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GatewayAlertRule.
// This includes values selected through modifiers, order, etc.
func (_m *GatewayAlertRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GatewayAlertRule.
// Note that you need to call GatewayAlertRule.Unwrap() before calling this method if this GatewayAlertRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GatewayAlertRule) Update() *GatewayAlertRuleUpdateOne {
	return NewGatewayAlertRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GatewayAlertRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GatewayAlertRule) Unwrap() *GatewayAlertRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GatewayAlertRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GatewayAlertRule) String() string {
	var builder strings.Builder
	builder.WriteString("GatewayAlertRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("metric=")
	builder.WriteString(_m.Metric)
	builder.WriteString(", ")
	builder.WriteString("operator=")
	builder.WriteString(_m.Operator)
	builder.WriteString(", ")
	builder.WriteString("threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.Threshold))
	builder.WriteString(", ")
	builder.WriteString("window_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.WindowSeconds))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GatewayAlertRules is a parsable slice of GatewayAlertRule.
type GatewayAlertRules []*GatewayAlertRule
