// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewayalertevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayAlertEventCreate is the builder for creating a GatewayAlertEvent entity.
type GatewayAlertEventCreate struct {
	config
	mutation *GatewayAlertEventMutation
	hooks    []Hook
}

// SetRuleID sets the "rule_id" field.
func (_c *GatewayAlertEventCreate) SetRuleID(v int) *GatewayAlertEventCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableRuleID(v *int) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetRuleID(*v)
	}
	return _c
}

// SetRuleName sets the "rule_name" field.
func (_c *GatewayAlertEventCreate) SetRuleName(v string) *GatewayAlertEventCreate {
	_c.mutation.SetRuleName(v)
	return _c
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableRuleName(v *string) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetRuleName(*v)
	}
	return _c
}

// SetMetric sets the "metric" field.
func (_c *GatewayAlertEventCreate) SetMetric(v string) *GatewayAlertEventCreate {
	_c.mutation.SetMetric(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *GatewayAlertEventCreate) SetValue(v float64) *GatewayAlertEventCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableValue(v *float64) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetThreshold sets the "threshold" field.
func (_c *GatewayAlertEventCreate) SetThreshold(v float64) *GatewayAlertEventCreate {
	_c.mutation.SetThreshold(v)
	return _c
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableThreshold(v *float64) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetThreshold(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GatewayAlertEventCreate) SetStatus(v string) *GatewayAlertEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableStatus(v *string) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAckBy sets the "ack_by" field.
func (_c *GatewayAlertEventCreate) SetAckBy(v int) *GatewayAlertEventCreate {
	_c.mutation.SetAckBy(v)
	return _c
}

// SetNillableAckBy sets the "ack_by" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableAckBy(v *int) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetAckBy(*v)
	}
	return _c
}

// SetAckAt sets the "ack_at" field.
func (_c *GatewayAlertEventCreate) SetAckAt(v time.Time) *GatewayAlertEventCreate {
	_c.mutation.SetAckAt(v)
	return _c
}

// SetNillableAckAt sets the "ack_at" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableAckAt(v *time.Time) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetAckAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GatewayAlertEventCreate) SetCreatedAt(v time.Time) *GatewayAlertEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GatewayAlertEventCreate) SetNillableCreatedAt(v *time.Time) *GatewayAlertEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the GatewayAlertEventMutation object of the builder.
func (_c *GatewayAlertEventCreate) Mutation() *GatewayAlertEventMutation {
	return _c.mutation
}

// Save creates the GatewayAlertEvent in the database.
func (_c *GatewayAlertEventCreate) Save(ctx context.Context) (*GatewayAlertEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GatewayAlertEventCreate) SaveX(ctx context.Context) *GatewayAlertEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayAlertEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayAlertEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GatewayAlertEventCreate) defaults() {
	if _, ok := _c.mutation.RuleName(); !ok {
		v := gatewayalertevent.DefaultRuleName
		_c.mutation.SetRuleName(v)
	}
	if _, ok := _c.mutation.Value(); !ok {
		v := gatewayalertevent.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Threshold(); !ok {
		v := gatewayalertevent.DefaultThreshold
		_c.mutation.SetThreshold(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := gatewayalertevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gatewayalertevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GatewayAlertEventCreate) check() error {
	if _, ok := _c.mutation.RuleName(); !ok {
		return &ValidationError{Name: "rule_name", err: errors.New(`ent: missing required field "GatewayAlertEvent.rule_name"`)}
	}
	if v, ok := _c.mutation.RuleName(); ok {
		if err := gatewayalertevent.RuleNameValidator(v); err != nil {
			return &ValidationError{Name: "rule_name", err: fmt.Errorf(`ent: validator failed for field "GatewayAlertEvent.rule_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metric(); !ok {
		return &ValidationError{Name: "metric", err: errors.New(`ent: missing required field "GatewayAlertEvent.metric"`)}
	}
	if v, ok := _c.mutation.Metric(); ok {
		if err := gatewayalertevent.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "GatewayAlertEvent.metric": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "GatewayAlertEvent.value"`)}
	}
	if _, ok := _c.mutation.Threshold(); !ok {
		return &ValidationError{Name: "threshold", err: errors.New(`ent: missing required field "GatewayAlertEvent.threshold"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GatewayAlertEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := gatewayalertevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GatewayAlertEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GatewayAlertEvent.created_at"`)}
	}
	return nil
}

func (_c *GatewayAlertEventCreate) sqlSave(ctx context.Context) (*GatewayAlertEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GatewayAlertEventCreate) createSpec() (*GatewayAlertEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &GatewayAlertEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gatewayalertevent.Table, sqlgraph.NewFieldSpec(gatewayalertevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(gatewayalertevent.FieldRuleID, field.TypeInt, value)
		_node.RuleID = &value
	}
	if value, ok := _c.mutation.RuleName(); ok {
		_spec.SetField(gatewayalertevent.FieldRuleName, field.TypeString, value)
		_node.RuleName = value
	}
	if value, ok := _c.mutation.Metric(); ok {
		_spec.SetField(gatewayalertevent.FieldMetric, field.TypeString, value)
		_node.Metric = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(gatewayalertevent.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Threshold(); ok {
		_spec.SetField(gatewayalertevent.FieldThreshold, field.TypeFloat64, value)
		_node.Threshold = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(gatewayalertevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AckBy(); ok {
		_spec.SetField(gatewayalertevent.FieldAckBy, field.TypeInt, value)
		_node.AckBy = &value
	}
	if value, ok := _c.mutation.AckAt(); ok {
		_spec.SetField(gatewayalertevent.FieldAckAt, field.TypeTime, value)
		_node.AckAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gatewayalertevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// GatewayAlertEventCreateBulk is the builder for creating many GatewayAlertEvent entities in bulk.
type GatewayAlertEventCreateBulk struct {
	config
	err      error
	builders []*GatewayAlertEventCreate
}

// Save creates the GatewayAlertEvent entities in the database.
func (_c *GatewayAlertEventCreateBulk) Save(ctx context.Context) ([]*GatewayAlertEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GatewayAlertEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GatewayAlertEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GatewayAlertEventCreateBulk) SaveX(ctx context.Context) []*GatewayAlertEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayAlertEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayAlertEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
