// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewayauditlog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayAuditLogCreate is the builder for creating a GatewayAuditLog entity.
type GatewayAuditLogCreate struct {
	config
	mutation *GatewayAuditLogMutation
	hooks    []Hook
}

// SetActorID sets the "actor_id" field.
func (_c *GatewayAuditLogCreate) SetActorID(v int) *GatewayAuditLogCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *GatewayAuditLogCreate) SetNillableActorID(v *int) *GatewayAuditLogCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetActorName sets the "actor_name" field.
func (_c *GatewayAuditLogCreate) SetActorName(v string) *GatewayAuditLogCreate {
	_c.mutation.SetActorName(v)
	return _c
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_c *GatewayAuditLogCreate) SetNillableActorName(v *string) *GatewayAuditLogCreate {
	if v != nil {
		_c.SetActorName(*v)
	}
	return _c
}

// SetActorRole sets the "actor_role" field.
func (_c *GatewayAuditLogCreate) SetActorRole(v string) *GatewayAuditLogCreate {
	_c.mutation.SetActorRole(v)
	return _c
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_c *GatewayAuditLogCreate) SetNillableActorRole(v *string) *GatewayAuditLogCreate {
	if v != nil {
		_c.SetActorRole(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *GatewayAuditLogCreate) SetAction(v string) *GatewayAuditLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *GatewayAuditLogCreate) SetTargetType(v string) *GatewayAuditLogCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_c *GatewayAuditLogCreate) SetNillableTargetType(v *string) *GatewayAuditLogCreate {
	if v != nil {
		_c.SetTargetType(*v)
	}
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *GatewayAuditLogCreate) SetTargetID(v string) *GatewayAuditLogCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_c *GatewayAuditLogCreate) SetNillableTargetID(v *string) *GatewayAuditLogCreate {
	if v != nil {
		_c.SetTargetID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *GatewayAuditLogCreate) SetMetadata(v map[string]interface{}) *GatewayAuditLogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GatewayAuditLogCreate) SetCreatedAt(v time.Time) *GatewayAuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GatewayAuditLogCreate) SetNillableCreatedAt(v *time.Time) *GatewayAuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the GatewayAuditLogMutation object of the builder.
func (_c *GatewayAuditLogCreate) Mutation() *GatewayAuditLogMutation {
	return _c.mutation
}

// Save creates the GatewayAuditLog in the database.
func (_c *GatewayAuditLogCreate) Save(ctx context.Context) (*GatewayAuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GatewayAuditLogCreate) SaveX(ctx context.Context) *GatewayAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayAuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayAuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GatewayAuditLogCreate) defaults() {
	if _, ok := _c.mutation.ActorID(); !ok {
		v := gatewayauditlog.DefaultActorID
		_c.mutation.SetActorID(v)
	}
	if _, ok := _c.mutation.ActorName(); !ok {
		v := gatewayauditlog.DefaultActorName
		_c.mutation.SetActorName(v)
	}
	if _, ok := _c.mutation.ActorRole(); !ok {
		v := gatewayauditlog.DefaultActorRole
		_c.mutation.SetActorRole(v)
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		v := gatewayauditlog.DefaultTargetType
		_c.mutation.SetTargetType(v)
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		v := gatewayauditlog.DefaultTargetID
		_c.mutation.SetTargetID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gatewayauditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GatewayAuditLogCreate) check() error {
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`ent: missing required field "GatewayAuditLog.actor_id"`)}
	}
	if _, ok := _c.mutation.ActorName(); !ok {
		return &ValidationError{Name: "actor_name", err: errors.New(`ent: missing required field "GatewayAuditLog.actor_name"`)}
	}
	if v, ok := _c.mutation.ActorName(); ok {
		if err := gatewayauditlog.ActorNameValidator(v); err != nil {
			return &ValidationError{Name: "actor_name", err: fmt.Errorf(`ent: validator failed for field "GatewayAuditLog.actor_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorRole(); !ok {
		return &ValidationError{Name: "actor_role", err: errors.New(`ent: missing required field "GatewayAuditLog.actor_role"`)}
	}
	if v, ok := _c.mutation.ActorRole(); ok {
		if err := gatewayauditlog.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "GatewayAuditLog.actor_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "GatewayAuditLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := gatewayauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "GatewayAuditLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "GatewayAuditLog.target_type"`)}
	}
	if v, ok := _c.mutation.TargetType(); ok {
		if err := gatewayauditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "GatewayAuditLog.target_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "GatewayAuditLog.target_id"`)}
	}
	if v, ok := _c.mutation.TargetID(); ok {
		if err := gatewayauditlog.TargetIDValidator(v); err != nil {
			return &ValidationError{Name: "target_id", err: fmt.Errorf(`ent: validator failed for field "GatewayAuditLog.target_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GatewayAuditLog.created_at"`)}
	}
	return nil
}

func (_c *GatewayAuditLogCreate) sqlSave(ctx context.Context) (*GatewayAuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GatewayAuditLogCreate) createSpec() (*GatewayAuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &GatewayAuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gatewayauditlog.Table, sqlgraph.NewFieldSpec(gatewayauditlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(gatewayauditlog.FieldActorID, field.TypeInt, value)
		_node.ActorID = value
	}
	if value, ok := _c.mutation.ActorName(); ok {
		_spec.SetField(gatewayauditlog.FieldActorName, field.TypeString, value)
		_node.ActorName = value
	}
	if value, ok := _c.mutation.ActorRole(); ok {
		_spec.SetField(gatewayauditlog.FieldActorRole, field.TypeString, value)
		_node.ActorRole = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(gatewayauditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(gatewayauditlog.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(gatewayauditlog.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(gatewayauditlog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gatewayauditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// GatewayAuditLogCreateBulk is the builder for creating many GatewayAuditLog entities in bulk.
type GatewayAuditLogCreateBulk struct {
	config
	err      error
	builders []*GatewayAuditLogCreate
}

// Save creates the GatewayAuditLog entities in the database.
func (_c *GatewayAuditLogCreateBulk) Save(ctx context.Context) ([]*GatewayAuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GatewayAuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GatewayAuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GatewayAuditLogCreateBulk) SaveX(ctx context.Context) []*GatewayAuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayAuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayAuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
