// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewaymodel"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayModelCreate is the builder for creating a GatewayModel entity.
type GatewayModelCreate struct {
	config
	mutation *GatewayModelMutation
	hooks    []Hook
}

// SetModelID sets the "model_id" field.
func (_c *GatewayModelCreate) SetModelID(v string) *GatewayModelCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetOwnedBy sets the "owned_by" field.
func (_c *GatewayModelCreate) SetOwnedBy(v string) *GatewayModelCreate {
	_c.mutation.SetOwnedBy(v)
	return _c
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableOwnedBy(v *string) *GatewayModelCreate {
	if v != nil {
		_c.SetOwnedBy(*v)
	}
	return _c
}

// SetCreatedUnix sets the "created_unix" field.
func (_c *GatewayModelCreate) SetCreatedUnix(v int64) *GatewayModelCreate {
	_c.mutation.SetCreatedUnix(v)
	return _c
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableCreatedUnix(v *int64) *GatewayModelCreate {
	if v != nil {
		_c.SetCreatedUnix(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *GatewayModelCreate) SetEnabled(v bool) *GatewayModelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableEnabled(v *bool) *GatewayModelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *GatewayModelCreate) SetSource(v string) *GatewayModelCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableSource(v *string) *GatewayModelCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetContextWindowTokens sets the "context_window_tokens" field.
func (_c *GatewayModelCreate) SetContextWindowTokens(v int64) *GatewayModelCreate {
	_c.mutation.SetContextWindowTokens(v)
	return _c
}

// SetNillableContextWindowTokens sets the "context_window_tokens" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableContextWindowTokens(v *int64) *GatewayModelCreate {
	if v != nil {
		_c.SetContextWindowTokens(*v)
	}
	return _c
}

// SetContextCompactTokens sets the "context_compact_tokens" field.
func (_c *GatewayModelCreate) SetContextCompactTokens(v int64) *GatewayModelCreate {
	_c.mutation.SetContextCompactTokens(v)
	return _c
}

// SetNillableContextCompactTokens sets the "context_compact_tokens" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableContextCompactTokens(v *int64) *GatewayModelCreate {
	if v != nil {
		_c.SetContextCompactTokens(*v)
	}
	return _c
}

// SetContextHardTokens sets the "context_hard_tokens" field.
func (_c *GatewayModelCreate) SetContextHardTokens(v int64) *GatewayModelCreate {
	_c.mutation.SetContextHardTokens(v)
	return _c
}

// SetNillableContextHardTokens sets the "context_hard_tokens" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableContextHardTokens(v *int64) *GatewayModelCreate {
	if v != nil {
		_c.SetContextHardTokens(*v)
	}
	return _c
}

// SetContextCompactBytes sets the "context_compact_bytes" field.
func (_c *GatewayModelCreate) SetContextCompactBytes(v int64) *GatewayModelCreate {
	_c.mutation.SetContextCompactBytes(v)
	return _c
}

// SetNillableContextCompactBytes sets the "context_compact_bytes" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableContextCompactBytes(v *int64) *GatewayModelCreate {
	if v != nil {
		_c.SetContextCompactBytes(*v)
	}
	return _c
}

// SetContextHardBytes sets the "context_hard_bytes" field.
func (_c *GatewayModelCreate) SetContextHardBytes(v int64) *GatewayModelCreate {
	_c.mutation.SetContextHardBytes(v)
	return _c
}

// SetNillableContextHardBytes sets the "context_hard_bytes" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableContextHardBytes(v *int64) *GatewayModelCreate {
	if v != nil {
		_c.SetContextHardBytes(*v)
	}
	return _c
}

// SetContextKeepItems sets the "context_keep_items" field.
func (_c *GatewayModelCreate) SetContextKeepItems(v int) *GatewayModelCreate {
	_c.mutation.SetContextKeepItems(v)
	return _c
}

// SetNillableContextKeepItems sets the "context_keep_items" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableContextKeepItems(v *int) *GatewayModelCreate {
	if v != nil {
		_c.SetContextKeepItems(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *GatewayModelCreate) SetLastSeenAt(v time.Time) *GatewayModelCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableLastSeenAt(v *time.Time) *GatewayModelCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GatewayModelCreate) SetCreatedAt(v time.Time) *GatewayModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableCreatedAt(v *time.Time) *GatewayModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GatewayModelCreate) SetUpdatedAt(v time.Time) *GatewayModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GatewayModelCreate) SetNillableUpdatedAt(v *time.Time) *GatewayModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GatewayModelMutation object of the builder.
func (_c *GatewayModelCreate) Mutation() *GatewayModelMutation {
	return _c.mutation
}

// Save creates the GatewayModel in the database.
func (_c *GatewayModelCreate) Save(ctx context.Context) (*GatewayModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GatewayModelCreate) SaveX(ctx context.Context) *GatewayModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GatewayModelCreate) defaults() {
	if _, ok := _c.mutation.OwnedBy(); !ok {
		v := gatewaymodel.DefaultOwnedBy
		_c.mutation.SetOwnedBy(v)
	}
	if _, ok := _c.mutation.CreatedUnix(); !ok {
		v := gatewaymodel.DefaultCreatedUnix
		_c.mutation.SetCreatedUnix(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := gatewaymodel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := gatewaymodel.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.ContextWindowTokens(); !ok {
		v := gatewaymodel.DefaultContextWindowTokens
		_c.mutation.SetContextWindowTokens(v)
	}
	if _, ok := _c.mutation.ContextCompactTokens(); !ok {
		v := gatewaymodel.DefaultContextCompactTokens
		_c.mutation.SetContextCompactTokens(v)
	}
	if _, ok := _c.mutation.ContextHardTokens(); !ok {
		v := gatewaymodel.DefaultContextHardTokens
		_c.mutation.SetContextHardTokens(v)
	}
	if _, ok := _c.mutation.ContextCompactBytes(); !ok {
		v := gatewaymodel.DefaultContextCompactBytes
		_c.mutation.SetContextCompactBytes(v)
	}
	if _, ok := _c.mutation.ContextHardBytes(); !ok {
		v := gatewaymodel.DefaultContextHardBytes
		_c.mutation.SetContextHardBytes(v)
	}
	if _, ok := _c.mutation.ContextKeepItems(); !ok {
		v := gatewaymodel.DefaultContextKeepItems
		_c.mutation.SetContextKeepItems(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gatewaymodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gatewaymodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GatewayModelCreate) check() error {
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "GatewayModel.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := gatewaymodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnedBy(); !ok {
		return &ValidationError{Name: "owned_by", err: errors.New(`ent: missing required field "GatewayModel.owned_by"`)}
	}
	if v, ok := _c.mutation.OwnedBy(); ok {
		if err := gatewaymodel.OwnedByValidator(v); err != nil {
			return &ValidationError{Name: "owned_by", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.owned_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedUnix(); !ok {
		return &ValidationError{Name: "created_unix", err: errors.New(`ent: missing required field "GatewayModel.created_unix"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "GatewayModel.enabled"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "GatewayModel.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := gatewaymodel.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContextWindowTokens(); !ok {
		return &ValidationError{Name: "context_window_tokens", err: errors.New(`ent: missing required field "GatewayModel.context_window_tokens"`)}
	}
	if v, ok := _c.mutation.ContextWindowTokens(); ok {
		if err := gatewaymodel.ContextWindowTokensValidator(v); err != nil {
			return &ValidationError{Name: "context_window_tokens", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.context_window_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContextCompactTokens(); !ok {
		return &ValidationError{Name: "context_compact_tokens", err: errors.New(`ent: missing required field "GatewayModel.context_compact_tokens"`)}
	}
	if v, ok := _c.mutation.ContextCompactTokens(); ok {
		if err := gatewaymodel.ContextCompactTokensValidator(v); err != nil {
			return &ValidationError{Name: "context_compact_tokens", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.context_compact_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContextHardTokens(); !ok {
		return &ValidationError{Name: "context_hard_tokens", err: errors.New(`ent: missing required field "GatewayModel.context_hard_tokens"`)}
	}
	if v, ok := _c.mutation.ContextHardTokens(); ok {
		if err := gatewaymodel.ContextHardTokensValidator(v); err != nil {
			return &ValidationError{Name: "context_hard_tokens", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.context_hard_tokens": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContextCompactBytes(); !ok {
		return &ValidationError{Name: "context_compact_bytes", err: errors.New(`ent: missing required field "GatewayModel.context_compact_bytes"`)}
	}
	if v, ok := _c.mutation.ContextCompactBytes(); ok {
		if err := gatewaymodel.ContextCompactBytesValidator(v); err != nil {
			return &ValidationError{Name: "context_compact_bytes", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.context_compact_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContextHardBytes(); !ok {
		return &ValidationError{Name: "context_hard_bytes", err: errors.New(`ent: missing required field "GatewayModel.context_hard_bytes"`)}
	}
	if v, ok := _c.mutation.ContextHardBytes(); ok {
		if err := gatewaymodel.ContextHardBytesValidator(v); err != nil {
			return &ValidationError{Name: "context_hard_bytes", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.context_hard_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContextKeepItems(); !ok {
		return &ValidationError{Name: "context_keep_items", err: errors.New(`ent: missing required field "GatewayModel.context_keep_items"`)}
	}
	if v, ok := _c.mutation.ContextKeepItems(); ok {
		if err := gatewaymodel.ContextKeepItemsValidator(v); err != nil {
			return &ValidationError{Name: "context_keep_items", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.context_keep_items": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GatewayModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GatewayModel.updated_at"`)}
	}
	return nil
}

func (_c *GatewayModelCreate) sqlSave(ctx context.Context) (*GatewayModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GatewayModelCreate) createSpec() (*GatewayModel, *sqlgraph.CreateSpec) {
	var (
		_node = &GatewayModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gatewaymodel.Table, sqlgraph.NewFieldSpec(gatewaymodel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(gatewaymodel.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.OwnedBy(); ok {
		_spec.SetField(gatewaymodel.FieldOwnedBy, field.TypeString, value)
		_node.OwnedBy = value
	}
	if value, ok := _c.mutation.CreatedUnix(); ok {
		_spec.SetField(gatewaymodel.FieldCreatedUnix, field.TypeInt64, value)
		_node.CreatedUnix = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(gatewaymodel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(gatewaymodel.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.ContextWindowTokens(); ok {
		_spec.SetField(gatewaymodel.FieldContextWindowTokens, field.TypeInt64, value)
		_node.ContextWindowTokens = value
	}
	if value, ok := _c.mutation.ContextCompactTokens(); ok {
		_spec.SetField(gatewaymodel.FieldContextCompactTokens, field.TypeInt64, value)
		_node.ContextCompactTokens = value
	}
	if value, ok := _c.mutation.ContextHardTokens(); ok {
		_spec.SetField(gatewaymodel.FieldContextHardTokens, field.TypeInt64, value)
		_node.ContextHardTokens = value
	}
	if value, ok := _c.mutation.ContextCompactBytes(); ok {
		_spec.SetField(gatewaymodel.FieldContextCompactBytes, field.TypeInt64, value)
		_node.ContextCompactBytes = value
	}
	if value, ok := _c.mutation.ContextHardBytes(); ok {
		_spec.SetField(gatewaymodel.FieldContextHardBytes, field.TypeInt64, value)
		_node.ContextHardBytes = value
	}
	if value, ok := _c.mutation.ContextKeepItems(); ok {
		_spec.SetField(gatewaymodel.FieldContextKeepItems, field.TypeInt, value)
		_node.ContextKeepItems = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(gatewaymodel.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gatewaymodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaymodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GatewayModelCreateBulk is the builder for creating many GatewayModel entities in bulk.
type GatewayModelCreateBulk struct {
	config
	err      error
	builders []*GatewayModelCreate
}

// Save creates the GatewayModel entities in the database.
func (_c *GatewayModelCreateBulk) Save(ctx context.Context) ([]*GatewayModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GatewayModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GatewayModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GatewayModelCreateBulk) SaveX(ctx context.Context) []*GatewayModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
