// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"server/internal/data/model/ent/gatewayapikey"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GatewayAPIKey is the model entity for the GatewayAPIKey schema.
type GatewayAPIKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID *int `json:"owner_user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// KeyHash holds the value of the "key_hash" field.
	KeyHash string `json:"-"`
	// PlainKey holds the value of the "plain_key" field.
	PlainKey string `json:"-"`
	// KeyPrefix holds the value of the "key_prefix" field.
	KeyPrefix string `json:"key_prefix,omitempty"`
	// KeyLast4 holds the value of the "key_last4" field.
	KeyLast4 string `json:"key_last4,omitempty"`
	// Disabled holds the value of the "disabled" field.
	Disabled bool `json:"disabled,omitempty"`
	// QuotaRequests holds the value of the "quota_requests" field.
	QuotaRequests int64 `json:"quota_requests,omitempty"`
	// QuotaTotalTokens holds the value of the "quota_total_tokens" field.
	QuotaTotalTokens int64 `json:"quota_total_tokens,omitempty"`
	// AllowedModels holds the value of the "allowed_models" field.
	AllowedModels []string `json:"allowed_models,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GatewayAPIKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gatewayapikey.FieldAllowedModels:
			values[i] = new([]byte)
		case gatewayapikey.FieldDisabled:
			values[i] = new(sql.NullBool)
		case gatewayapikey.FieldID, gatewayapikey.FieldOwnerUserID, gatewayapikey.FieldQuotaRequests, gatewayapikey.FieldQuotaTotalTokens:
			values[i] = new(sql.NullInt64)
		case gatewayapikey.FieldName, gatewayapikey.FieldKeyHash, gatewayapikey.FieldPlainKey, gatewayapikey.FieldKeyPrefix, gatewayapikey.FieldKeyLast4:
			values[i] = new(sql.NullString)
		case gatewayapikey.FieldLastUsedAt, gatewayapikey.FieldCreatedAt, gatewayapikey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GatewayAPIKey fields.
func (_m *GatewayAPIKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gatewayapikey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gatewayapikey.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = new(int)
				*_m.OwnerUserID = int(value.Int64)
			}
		case gatewayapikey.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case gatewayapikey.FieldKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_hash", values[i])
			} else if value.Valid {
				_m.KeyHash = value.String
			}
		case gatewayapikey.FieldPlainKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plain_key", values[i])
			} else if value.Valid {
				_m.PlainKey = value.String
			}
		case gatewayapikey.FieldKeyPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_prefix", values[i])
			} else if value.Valid {
				_m.KeyPrefix = value.String
			}
		case gatewayapikey.FieldKeyLast4:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_last4", values[i])
			} else if value.Valid {
				_m.KeyLast4 = value.String
			}
		case gatewayapikey.FieldDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field disabled", values[i])
			} else if value.Valid {
				_m.Disabled = value.Bool
			}
		case gatewayapikey.FieldQuotaRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_requests", values[i])
			} else if value.Valid {
				_m.QuotaRequests = value.Int64
			}
		case gatewayapikey.FieldQuotaTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_total_tokens", values[i])
			} else if value.Valid {
				_m.QuotaTotalTokens = value.Int64
			}
		case gatewayapikey.FieldAllowedModels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_models", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedModels); err != nil {
					return fmt.Errorf("unmarshal field allowed_models: %w", err)
				}
			}
		case gatewayapikey.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case gatewayapikey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gatewayapikey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GatewayAPIKey.
// This includes values selected through modifiers, order, etc.
func (_m *GatewayAPIKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GatewayAPIKey.
// Note that you need to call GatewayAPIKey.Unwrap() before calling this method if this GatewayAPIKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GatewayAPIKey) Update() *GatewayAPIKeyUpdateOne {
	return NewGatewayAPIKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GatewayAPIKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GatewayAPIKey) Unwrap() *GatewayAPIKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GatewayAPIKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GatewayAPIKey) String() string {
	var builder strings.Builder
	builder.WriteString("GatewayAPIKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.OwnerUserID; v != nil {
		builder.WriteString("owner_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("key_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("plain_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("key_prefix=")
	builder.WriteString(_m.KeyPrefix)
	builder.WriteString(", ")
	builder.WriteString("key_last4=")
	builder.WriteString(_m.KeyLast4)
	builder.WriteString(", ")
	builder.WriteString("disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Disabled))
	builder.WriteString(", ")
	builder.WriteString("quota_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaRequests))
	builder.WriteString(", ")
	builder.WriteString("quota_total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaTotalTokens))
	builder.WriteString(", ")
	builder.WriteString("allowed_models=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedModels))
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GatewayAPIKeys is a parsable slice of GatewayAPIKey.
type GatewayAPIKeys []*GatewayAPIKey
