// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/gatewaypolicy"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GatewayPolicy is the model entity for the GatewayPolicy schema.
type GatewayPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int `json:"api_key_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// Rpm holds the value of the "rpm" field.
	Rpm int64 `json:"rpm,omitempty"`
	// Tpm holds the value of the "tpm" field.
	Tpm int64 `json:"tpm,omitempty"`
	// DailyRequests holds the value of the "daily_requests" field.
	DailyRequests int64 `json:"daily_requests,omitempty"`
	// MonthlyRequests holds the value of the "monthly_requests" field.
	MonthlyRequests int64 `json:"monthly_requests,omitempty"`
	// DailyTokens holds the value of the "daily_tokens" field.
	DailyTokens int64 `json:"daily_tokens,omitempty"`
	// MonthlyTokens holds the value of the "monthly_tokens" field.
	MonthlyTokens int64 `json:"monthly_tokens,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GatewayPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gatewaypolicy.FieldID, gatewaypolicy.FieldAPIKeyID, gatewaypolicy.FieldRpm, gatewaypolicy.FieldTpm, gatewaypolicy.FieldDailyRequests, gatewaypolicy.FieldMonthlyRequests, gatewaypolicy.FieldDailyTokens, gatewaypolicy.FieldMonthlyTokens:
			values[i] = new(sql.NullInt64)
		case gatewaypolicy.FieldModelID:
			values[i] = new(sql.NullString)
		case gatewaypolicy.FieldCreatedAt, gatewaypolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GatewayPolicy fields.
func (_m *GatewayPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gatewaypolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gatewaypolicy.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		case gatewaypolicy.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case gatewaypolicy.FieldRpm:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rpm", values[i])
			} else if value.Valid {
				_m.Rpm = value.Int64
			}
		case gatewaypolicy.FieldTpm:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tpm", values[i])
			} else if value.Valid {
				_m.Tpm = value.Int64
			}
		case gatewaypolicy.FieldDailyRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_requests", values[i])
			} else if value.Valid {
				_m.DailyRequests = value.Int64
			}
		case gatewaypolicy.FieldMonthlyRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_requests", values[i])
			} else if value.Valid {
				_m.MonthlyRequests = value.Int64
			}
		case gatewaypolicy.FieldDailyTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_tokens", values[i])
			} else if value.Valid {
				_m.DailyTokens = value.Int64
			}
		case gatewaypolicy.FieldMonthlyTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_tokens", values[i])
			} else if value.Valid {
				_m.MonthlyTokens = value.Int64
			}
		case gatewaypolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gatewaypolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GatewayPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *GatewayPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GatewayPolicy.
// Note that you need to call GatewayPolicy.Unwrap() before calling this method if this GatewayPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GatewayPolicy) Update() *GatewayPolicyUpdateOne {
	return NewGatewayPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GatewayPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GatewayPolicy) Unwrap() *GatewayPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GatewayPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GatewayPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("GatewayPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("rpm=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rpm))
	builder.WriteString(", ")
	builder.WriteString("tpm=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tpm))
	builder.WriteString(", ")
	builder.WriteString("daily_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyRequests))
	builder.WriteString(", ")
	builder.WriteString("monthly_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyRequests))
	builder.WriteString(", ")
	builder.WriteString("daily_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyTokens))
	builder.WriteString(", ")
	builder.WriteString("monthly_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyTokens))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GatewayPolicies is a parsable slice of GatewayPolicy.
type GatewayPolicies []*GatewayPolicy
