// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewaycontextsummary"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayContextSummaryCreate is the builder for creating a GatewayContextSummary entity.
type GatewayContextSummaryCreate struct {
	config
	mutation *GatewayContextSummaryMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *GatewayContextSummaryCreate) SetSessionID(v string) *GatewayContextSummaryCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *GatewayContextSummaryCreate) SetAPIKeyID(v int) *GatewayContextSummaryCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableAPIKeyID(v *int) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetAPIKeyPrefix sets the "api_key_prefix" field.
func (_c *GatewayContextSummaryCreate) SetAPIKeyPrefix(v string) *GatewayContextSummaryCreate {
	_c.mutation.SetAPIKeyPrefix(v)
	return _c
}

// SetNillableAPIKeyPrefix sets the "api_key_prefix" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableAPIKeyPrefix(v *string) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetAPIKeyPrefix(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *GatewayContextSummaryCreate) SetSummary(v string) *GatewayContextSummaryCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableSummary(v *string) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetSummaryTokens sets the "summary_tokens" field.
func (_c *GatewayContextSummaryCreate) SetSummaryTokens(v int64) *GatewayContextSummaryCreate {
	_c.mutation.SetSummaryTokens(v)
	return _c
}

// SetNillableSummaryTokens sets the "summary_tokens" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableSummaryTokens(v *int64) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetSummaryTokens(*v)
	}
	return _c
}

// SetCompactionCount sets the "compaction_count" field.
func (_c *GatewayContextSummaryCreate) SetCompactionCount(v int) *GatewayContextSummaryCreate {
	_c.mutation.SetCompactionCount(v)
	return _c
}

// SetNillableCompactionCount sets the "compaction_count" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableCompactionCount(v *int) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetCompactionCount(*v)
	}
	return _c
}

// SetLastRequestID sets the "last_request_id" field.
func (_c *GatewayContextSummaryCreate) SetLastRequestID(v string) *GatewayContextSummaryCreate {
	_c.mutation.SetLastRequestID(v)
	return _c
}

// SetNillableLastRequestID sets the "last_request_id" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableLastRequestID(v *string) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetLastRequestID(*v)
	}
	return _c
}

// SetLastReason sets the "last_reason" field.
func (_c *GatewayContextSummaryCreate) SetLastReason(v string) *GatewayContextSummaryCreate {
	_c.mutation.SetLastReason(v)
	return _c
}

// SetNillableLastReason sets the "last_reason" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableLastReason(v *string) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetLastReason(*v)
	}
	return _c
}

// SetLastOriginalBytes sets the "last_original_bytes" field.
func (_c *GatewayContextSummaryCreate) SetLastOriginalBytes(v int64) *GatewayContextSummaryCreate {
	_c.mutation.SetLastOriginalBytes(v)
	return _c
}

// SetNillableLastOriginalBytes sets the "last_original_bytes" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableLastOriginalBytes(v *int64) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetLastOriginalBytes(*v)
	}
	return _c
}

// SetLastCompactedBytes sets the "last_compacted_bytes" field.
func (_c *GatewayContextSummaryCreate) SetLastCompactedBytes(v int64) *GatewayContextSummaryCreate {
	_c.mutation.SetLastCompactedBytes(v)
	return _c
}

// SetNillableLastCompactedBytes sets the "last_compacted_bytes" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableLastCompactedBytes(v *int64) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetLastCompactedBytes(*v)
	}
	return _c
}

// SetLastOriginalTokens sets the "last_original_tokens" field.
func (_c *GatewayContextSummaryCreate) SetLastOriginalTokens(v int64) *GatewayContextSummaryCreate {
	_c.mutation.SetLastOriginalTokens(v)
	return _c
}

// SetNillableLastOriginalTokens sets the "last_original_tokens" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableLastOriginalTokens(v *int64) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetLastOriginalTokens(*v)
	}
	return _c
}

// SetLastCompactedTokens sets the "last_compacted_tokens" field.
func (_c *GatewayContextSummaryCreate) SetLastCompactedTokens(v int64) *GatewayContextSummaryCreate {
	_c.mutation.SetLastCompactedTokens(v)
	return _c
}

// SetNillableLastCompactedTokens sets the "last_compacted_tokens" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableLastCompactedTokens(v *int64) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetLastCompactedTokens(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *GatewayContextSummaryCreate) SetLastError(v string) *GatewayContextSummaryCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableLastError(v *string) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GatewayContextSummaryCreate) SetCreatedAt(v time.Time) *GatewayContextSummaryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableCreatedAt(v *time.Time) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GatewayContextSummaryCreate) SetUpdatedAt(v time.Time) *GatewayContextSummaryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GatewayContextSummaryCreate) SetNillableUpdatedAt(v *time.Time) *GatewayContextSummaryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GatewayContextSummaryMutation object of the builder.
func (_c *GatewayContextSummaryCreate) Mutation() *GatewayContextSummaryMutation {
	return _c.mutation
}

// Save creates the GatewayContextSummary in the database.
func (_c *GatewayContextSummaryCreate) Save(ctx context.Context) (*GatewayContextSummary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GatewayContextSummaryCreate) SaveX(ctx context.Context) *GatewayContextSummary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayContextSummaryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayContextSummaryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GatewayContextSummaryCreate) defaults() {
	if _, ok := _c.mutation.APIKeyPrefix(); !ok {
		v := gatewaycontextsummary.DefaultAPIKeyPrefix
		_c.mutation.SetAPIKeyPrefix(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := gatewaycontextsummary.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.SummaryTokens(); !ok {
		v := gatewaycontextsummary.DefaultSummaryTokens
		_c.mutation.SetSummaryTokens(v)
	}
	if _, ok := _c.mutation.CompactionCount(); !ok {
		v := gatewaycontextsummary.DefaultCompactionCount
		_c.mutation.SetCompactionCount(v)
	}
	if _, ok := _c.mutation.LastRequestID(); !ok {
		v := gatewaycontextsummary.DefaultLastRequestID
		_c.mutation.SetLastRequestID(v)
	}
	if _, ok := _c.mutation.LastReason(); !ok {
		v := gatewaycontextsummary.DefaultLastReason
		_c.mutation.SetLastReason(v)
	}
	if _, ok := _c.mutation.LastOriginalBytes(); !ok {
		v := gatewaycontextsummary.DefaultLastOriginalBytes
		_c.mutation.SetLastOriginalBytes(v)
	}
	if _, ok := _c.mutation.LastCompactedBytes(); !ok {
		v := gatewaycontextsummary.DefaultLastCompactedBytes
		_c.mutation.SetLastCompactedBytes(v)
	}
	if _, ok := _c.mutation.LastOriginalTokens(); !ok {
		v := gatewaycontextsummary.DefaultLastOriginalTokens
		_c.mutation.SetLastOriginalTokens(v)
	}
	if _, ok := _c.mutation.LastCompactedTokens(); !ok {
		v := gatewaycontextsummary.DefaultLastCompactedTokens
		_c.mutation.SetLastCompactedTokens(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := gatewaycontextsummary.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gatewaycontextsummary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gatewaycontextsummary.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GatewayContextSummaryCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "GatewayContextSummary.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := gatewaycontextsummary.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "GatewayContextSummary.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyPrefix(); !ok {
		return &ValidationError{Name: "api_key_prefix", err: errors.New(`ent: missing required field "GatewayContextSummary.api_key_prefix"`)}
	}
	if v, ok := _c.mutation.APIKeyPrefix(); ok {
		if err := gatewaycontextsummary.APIKeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "api_key_prefix", err: fmt.Errorf(`ent: validator failed for field "GatewayContextSummary.api_key_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "GatewayContextSummary.summary"`)}
	}
	if _, ok := _c.mutation.SummaryTokens(); !ok {
		return &ValidationError{Name: "summary_tokens", err: errors.New(`ent: missing required field "GatewayContextSummary.summary_tokens"`)}
	}
	if _, ok := _c.mutation.CompactionCount(); !ok {
		return &ValidationError{Name: "compaction_count", err: errors.New(`ent: missing required field "GatewayContextSummary.compaction_count"`)}
	}
	if _, ok := _c.mutation.LastRequestID(); !ok {
		return &ValidationError{Name: "last_request_id", err: errors.New(`ent: missing required field "GatewayContextSummary.last_request_id"`)}
	}
	if v, ok := _c.mutation.LastRequestID(); ok {
		if err := gatewaycontextsummary.LastRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "last_request_id", err: fmt.Errorf(`ent: validator failed for field "GatewayContextSummary.last_request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastReason(); !ok {
		return &ValidationError{Name: "last_reason", err: errors.New(`ent: missing required field "GatewayContextSummary.last_reason"`)}
	}
	if v, ok := _c.mutation.LastReason(); ok {
		if err := gatewaycontextsummary.LastReasonValidator(v); err != nil {
			return &ValidationError{Name: "last_reason", err: fmt.Errorf(`ent: validator failed for field "GatewayContextSummary.last_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastOriginalBytes(); !ok {
		return &ValidationError{Name: "last_original_bytes", err: errors.New(`ent: missing required field "GatewayContextSummary.last_original_bytes"`)}
	}
	if _, ok := _c.mutation.LastCompactedBytes(); !ok {
		return &ValidationError{Name: "last_compacted_bytes", err: errors.New(`ent: missing required field "GatewayContextSummary.last_compacted_bytes"`)}
	}
	if _, ok := _c.mutation.LastOriginalTokens(); !ok {
		return &ValidationError{Name: "last_original_tokens", err: errors.New(`ent: missing required field "GatewayContextSummary.last_original_tokens"`)}
	}
	if _, ok := _c.mutation.LastCompactedTokens(); !ok {
		return &ValidationError{Name: "last_compacted_tokens", err: errors.New(`ent: missing required field "GatewayContextSummary.last_compacted_tokens"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "GatewayContextSummary.last_error"`)}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := gatewaycontextsummary.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "GatewayContextSummary.last_error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GatewayContextSummary.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GatewayContextSummary.updated_at"`)}
	}
	return nil
}

func (_c *GatewayContextSummaryCreate) sqlSave(ctx context.Context) (*GatewayContextSummary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GatewayContextSummaryCreate) createSpec() (*GatewayContextSummary, *sqlgraph.CreateSpec) {
	var (
		_node = &GatewayContextSummary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gatewaycontextsummary.Table, sqlgraph.NewFieldSpec(gatewaycontextsummary.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(gatewaycontextsummary.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(gatewaycontextsummary.FieldAPIKeyID, field.TypeInt, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.APIKeyPrefix(); ok {
		_spec.SetField(gatewaycontextsummary.FieldAPIKeyPrefix, field.TypeString, value)
		_node.APIKeyPrefix = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(gatewaycontextsummary.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.SummaryTokens(); ok {
		_spec.SetField(gatewaycontextsummary.FieldSummaryTokens, field.TypeInt64, value)
		_node.SummaryTokens = value
	}
	if value, ok := _c.mutation.CompactionCount(); ok {
		_spec.SetField(gatewaycontextsummary.FieldCompactionCount, field.TypeInt, value)
		_node.CompactionCount = value
	}
	if value, ok := _c.mutation.LastRequestID(); ok {
		_spec.SetField(gatewaycontextsummary.FieldLastRequestID, field.TypeString, value)
		_node.LastRequestID = value
	}
	if value, ok := _c.mutation.LastReason(); ok {
		_spec.SetField(gatewaycontextsummary.FieldLastReason, field.TypeString, value)
		_node.LastReason = value
	}
	if value, ok := _c.mutation.LastOriginalBytes(); ok {
		_spec.SetField(gatewaycontextsummary.FieldLastOriginalBytes, field.TypeInt64, value)
		_node.LastOriginalBytes = value
	}
	if value, ok := _c.mutation.LastCompactedBytes(); ok {
		_spec.SetField(gatewaycontextsummary.FieldLastCompactedBytes, field.TypeInt64, value)
		_node.LastCompactedBytes = value
	}
	if value, ok := _c.mutation.LastOriginalTokens(); ok {
		_spec.SetField(gatewaycontextsummary.FieldLastOriginalTokens, field.TypeInt64, value)
		_node.LastOriginalTokens = value
	}
	if value, ok := _c.mutation.LastCompactedTokens(); ok {
		_spec.SetField(gatewaycontextsummary.FieldLastCompactedTokens, field.TypeInt64, value)
		_node.LastCompactedTokens = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(gatewaycontextsummary.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gatewaycontextsummary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaycontextsummary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GatewayContextSummaryCreateBulk is the builder for creating many GatewayContextSummary entities in bulk.
type GatewayContextSummaryCreateBulk struct {
	config
	err      error
	builders []*GatewayContextSummaryCreate
}

// Save creates the GatewayContextSummary entities in the database.
func (_c *GatewayContextSummaryCreateBulk) Save(ctx context.Context) ([]*GatewayContextSummary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GatewayContextSummary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GatewayContextSummaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GatewayContextSummaryCreateBulk) SaveX(ctx context.Context) []*GatewayContextSummary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayContextSummaryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayContextSummaryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
