// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewaymodel"
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayModelUpdate is the builder for updating GatewayModel entities.
type GatewayModelUpdate struct {
	config
	hooks    []Hook
	mutation *GatewayModelMutation
}

// Where appends a list predicates to the GatewayModelUpdate builder.
func (_u *GatewayModelUpdate) Where(ps ...predicate.GatewayModel) *GatewayModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *GatewayModelUpdate) SetModelID(v string) *GatewayModelUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *GatewayModelUpdate) SetNillableModelID(v *string) *GatewayModelUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *GatewayModelUpdate) SetOwnedBy(v string) *GatewayModelUpdate {
	_u.mutation.SetOwnedBy(v)
	return _u
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_u *GatewayModelUpdate) SetNillableOwnedBy(v *string) *GatewayModelUpdate {
	if v != nil {
		_u.SetOwnedBy(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *GatewayModelUpdate) SetCreatedUnix(v int64) *GatewayModelUpdate {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *GatewayModelUpdate) SetNillableCreatedUnix(v *int64) *GatewayModelUpdate {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *GatewayModelUpdate) AddCreatedUnix(v int64) *GatewayModelUpdate {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GatewayModelUpdate) SetEnabled(v bool) *GatewayModelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GatewayModelUpdate) SetNillableEnabled(v *bool) *GatewayModelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *GatewayModelUpdate) SetSource(v string) *GatewayModelUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *GatewayModelUpdate) SetNillableSource(v *string) *GatewayModelUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *GatewayModelUpdate) SetLastSeenAt(v time.Time) *GatewayModelUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *GatewayModelUpdate) SetNillableLastSeenAt(v *time.Time) *GatewayModelUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *GatewayModelUpdate) ClearLastSeenAt() *GatewayModelUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GatewayModelUpdate) SetUpdatedAt(v time.Time) *GatewayModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GatewayModelMutation object of the builder.
func (_u *GatewayModelUpdate) Mutation() *GatewayModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GatewayModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GatewayModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GatewayModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gatewaymodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GatewayModelUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := gatewaymodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnedBy(); ok {
		if err := gatewaymodel.OwnedByValidator(v); err != nil {
			return &ValidationError{Name: "owned_by", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.owned_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := gatewaymodel.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.source": %w`, err)}
		}
	}
	return nil
}

func (_u *GatewayModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gatewaymodel.Table, gatewaymodel.Columns, sqlgraph.NewFieldSpec(gatewaymodel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(gatewaymodel.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(gatewaymodel.FieldOwnedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(gatewaymodel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(gatewaymodel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(gatewaymodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(gatewaymodel.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(gatewaymodel.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(gatewaymodel.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaymodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewaymodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GatewayModelUpdateOne is the builder for updating a single GatewayModel entity.
type GatewayModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GatewayModelMutation
}

// SetModelID sets the "model_id" field.
func (_u *GatewayModelUpdateOne) SetModelID(v string) *GatewayModelUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *GatewayModelUpdateOne) SetNillableModelID(v *string) *GatewayModelUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *GatewayModelUpdateOne) SetOwnedBy(v string) *GatewayModelUpdateOne {
	_u.mutation.SetOwnedBy(v)
	return _u
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_u *GatewayModelUpdateOne) SetNillableOwnedBy(v *string) *GatewayModelUpdateOne {
	if v != nil {
		_u.SetOwnedBy(*v)
	}
	return _u
}

// SetCreatedUnix sets the "created_unix" field.
func (_u *GatewayModelUpdateOne) SetCreatedUnix(v int64) *GatewayModelUpdateOne {
	_u.mutation.ResetCreatedUnix()
	_u.mutation.SetCreatedUnix(v)
	return _u
}

// SetNillableCreatedUnix sets the "created_unix" field if the given value is not nil.
func (_u *GatewayModelUpdateOne) SetNillableCreatedUnix(v *int64) *GatewayModelUpdateOne {
	if v != nil {
		_u.SetCreatedUnix(*v)
	}
	return _u
}

// AddCreatedUnix adds value to the "created_unix" field.
func (_u *GatewayModelUpdateOne) AddCreatedUnix(v int64) *GatewayModelUpdateOne {
	_u.mutation.AddCreatedUnix(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GatewayModelUpdateOne) SetEnabled(v bool) *GatewayModelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GatewayModelUpdateOne) SetNillableEnabled(v *bool) *GatewayModelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *GatewayModelUpdateOne) SetSource(v string) *GatewayModelUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *GatewayModelUpdateOne) SetNillableSource(v *string) *GatewayModelUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *GatewayModelUpdateOne) SetLastSeenAt(v time.Time) *GatewayModelUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *GatewayModelUpdateOne) SetNillableLastSeenAt(v *time.Time) *GatewayModelUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *GatewayModelUpdateOne) ClearLastSeenAt() *GatewayModelUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GatewayModelUpdateOne) SetUpdatedAt(v time.Time) *GatewayModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GatewayModelMutation object of the builder.
func (_u *GatewayModelUpdateOne) Mutation() *GatewayModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the GatewayModelUpdate builder.
func (_u *GatewayModelUpdateOne) Where(ps ...predicate.GatewayModel) *GatewayModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GatewayModelUpdateOne) Select(field string, fields ...string) *GatewayModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GatewayModel entity.
func (_u *GatewayModelUpdateOne) Save(ctx context.Context) (*GatewayModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GatewayModelUpdateOne) SaveX(ctx context.Context) *GatewayModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GatewayModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GatewayModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GatewayModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gatewaymodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GatewayModelUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := gatewaymodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnedBy(); ok {
		if err := gatewaymodel.OwnedByValidator(v); err != nil {
			return &ValidationError{Name: "owned_by", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.owned_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := gatewaymodel.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "GatewayModel.source": %w`, err)}
		}
	}
	return nil
}

func (_u *GatewayModelUpdateOne) sqlSave(ctx context.Context) (_node *GatewayModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gatewaymodel.Table, gatewaymodel.Columns, sqlgraph.NewFieldSpec(gatewaymodel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GatewayModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gatewaymodel.FieldID)
		for _, f := range fields {
			if !gatewaymodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gatewaymodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(gatewaymodel.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(gatewaymodel.FieldOwnedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedUnix(); ok {
		_spec.SetField(gatewaymodel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedUnix(); ok {
		_spec.AddField(gatewaymodel.FieldCreatedUnix, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(gatewaymodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(gatewaymodel.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(gatewaymodel.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(gatewaymodel.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewaymodel.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GatewayModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gatewaymodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
