// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/internal/data/model/ent/gatewayusagelog"
	"server/internal/data/model/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayUsageLogDelete is the builder for deleting a GatewayUsageLog entity.
type GatewayUsageLogDelete struct {
	config
	hooks    []Hook
	mutation *GatewayUsageLogMutation
}

// Where appends a list predicates to the GatewayUsageLogDelete builder.
func (_d *GatewayUsageLogDelete) Where(ps ...predicate.GatewayUsageLog) *GatewayUsageLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GatewayUsageLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayUsageLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GatewayUsageLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gatewayusagelog.Table, sqlgraph.NewFieldSpec(gatewayusagelog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GatewayUsageLogDeleteOne is the builder for deleting a single GatewayUsageLog entity.
type GatewayUsageLogDeleteOne struct {
	_d *GatewayUsageLogDelete
}

// Where appends a list predicates to the GatewayUsageLogDelete builder.
func (_d *GatewayUsageLogDeleteOne) Where(ps ...predicate.GatewayUsageLog) *GatewayUsageLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GatewayUsageLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gatewayusagelog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GatewayUsageLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
