// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/gatewayapikey"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GatewayAPIKeyCreate is the builder for creating a GatewayAPIKey entity.
type GatewayAPIKeyCreate struct {
	config
	mutation *GatewayAPIKeyMutation
	hooks    []Hook
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *GatewayAPIKeyCreate) SetOwnerUserID(v int) *GatewayAPIKeyCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableOwnerUserID(v *int) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetOwnerUserID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *GatewayAPIKeyCreate) SetName(v string) *GatewayAPIKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *GatewayAPIKeyCreate) SetKeyHash(v string) *GatewayAPIKeyCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetPlainKey sets the "plain_key" field.
func (_c *GatewayAPIKeyCreate) SetPlainKey(v string) *GatewayAPIKeyCreate {
	_c.mutation.SetPlainKey(v)
	return _c
}

// SetNillablePlainKey sets the "plain_key" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillablePlainKey(v *string) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetPlainKey(*v)
	}
	return _c
}

// SetKeyPrefix sets the "key_prefix" field.
func (_c *GatewayAPIKeyCreate) SetKeyPrefix(v string) *GatewayAPIKeyCreate {
	_c.mutation.SetKeyPrefix(v)
	return _c
}

// SetKeyLast4 sets the "key_last4" field.
func (_c *GatewayAPIKeyCreate) SetKeyLast4(v string) *GatewayAPIKeyCreate {
	_c.mutation.SetKeyLast4(v)
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *GatewayAPIKeyCreate) SetDisabled(v bool) *GatewayAPIKeyCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableDisabled(v *bool) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetQuotaRequests sets the "quota_requests" field.
func (_c *GatewayAPIKeyCreate) SetQuotaRequests(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaRequests(v)
	return _c
}

// SetNillableQuotaRequests sets the "quota_requests" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaRequests(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaRequests(*v)
	}
	return _c
}

// SetQuotaTotalTokens sets the "quota_total_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaTotalTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaTotalTokens(v)
	return _c
}

// SetNillableQuotaTotalTokens sets the "quota_total_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaTotalTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaTotalTokens(*v)
	}
	return _c
}

// SetQuotaDailyTokens sets the "quota_daily_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaDailyTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaDailyTokens(v)
	return _c
}

// SetNillableQuotaDailyTokens sets the "quota_daily_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaDailyTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaDailyTokens(*v)
	}
	return _c
}

// SetQuotaWeeklyTokens sets the "quota_weekly_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaWeeklyTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaWeeklyTokens(v)
	return _c
}

// SetNillableQuotaWeeklyTokens sets the "quota_weekly_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaWeeklyTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaWeeklyTokens(*v)
	}
	return _c
}

// SetQuotaDailyInputTokens sets the "quota_daily_input_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaDailyInputTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaDailyInputTokens(v)
	return _c
}

// SetNillableQuotaDailyInputTokens sets the "quota_daily_input_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaDailyInputTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaDailyInputTokens(*v)
	}
	return _c
}

// SetQuotaWeeklyInputTokens sets the "quota_weekly_input_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaWeeklyInputTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaWeeklyInputTokens(v)
	return _c
}

// SetNillableQuotaWeeklyInputTokens sets the "quota_weekly_input_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaWeeklyInputTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaWeeklyInputTokens(*v)
	}
	return _c
}

// SetQuotaDailyOutputTokens sets the "quota_daily_output_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaDailyOutputTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaDailyOutputTokens(v)
	return _c
}

// SetNillableQuotaDailyOutputTokens sets the "quota_daily_output_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaDailyOutputTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaDailyOutputTokens(*v)
	}
	return _c
}

// SetQuotaWeeklyOutputTokens sets the "quota_weekly_output_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaWeeklyOutputTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaWeeklyOutputTokens(v)
	return _c
}

// SetNillableQuotaWeeklyOutputTokens sets the "quota_weekly_output_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaWeeklyOutputTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaWeeklyOutputTokens(*v)
	}
	return _c
}

// SetQuotaDailyBillableInputTokens sets the "quota_daily_billable_input_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaDailyBillableInputTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaDailyBillableInputTokens(v)
	return _c
}

// SetNillableQuotaDailyBillableInputTokens sets the "quota_daily_billable_input_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaDailyBillableInputTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaDailyBillableInputTokens(*v)
	}
	return _c
}

// SetQuotaWeeklyBillableInputTokens sets the "quota_weekly_billable_input_tokens" field.
func (_c *GatewayAPIKeyCreate) SetQuotaWeeklyBillableInputTokens(v int64) *GatewayAPIKeyCreate {
	_c.mutation.SetQuotaWeeklyBillableInputTokens(v)
	return _c
}

// SetNillableQuotaWeeklyBillableInputTokens sets the "quota_weekly_billable_input_tokens" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableQuotaWeeklyBillableInputTokens(v *int64) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetQuotaWeeklyBillableInputTokens(*v)
	}
	return _c
}

// SetAllowedModels sets the "allowed_models" field.
func (_c *GatewayAPIKeyCreate) SetAllowedModels(v []string) *GatewayAPIKeyCreate {
	_c.mutation.SetAllowedModels(v)
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *GatewayAPIKeyCreate) SetLastUsedAt(v time.Time) *GatewayAPIKeyCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableLastUsedAt(v *time.Time) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GatewayAPIKeyCreate) SetCreatedAt(v time.Time) *GatewayAPIKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableCreatedAt(v *time.Time) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GatewayAPIKeyCreate) SetUpdatedAt(v time.Time) *GatewayAPIKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GatewayAPIKeyCreate) SetNillableUpdatedAt(v *time.Time) *GatewayAPIKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GatewayAPIKeyMutation object of the builder.
func (_c *GatewayAPIKeyCreate) Mutation() *GatewayAPIKeyMutation {
	return _c.mutation
}

// Save creates the GatewayAPIKey in the database.
func (_c *GatewayAPIKeyCreate) Save(ctx context.Context) (*GatewayAPIKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GatewayAPIKeyCreate) SaveX(ctx context.Context) *GatewayAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayAPIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayAPIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GatewayAPIKeyCreate) defaults() {
	if _, ok := _c.mutation.PlainKey(); !ok {
		v := gatewayapikey.DefaultPlainKey
		_c.mutation.SetPlainKey(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := gatewayapikey.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.QuotaRequests(); !ok {
		v := gatewayapikey.DefaultQuotaRequests
		_c.mutation.SetQuotaRequests(v)
	}
	if _, ok := _c.mutation.QuotaTotalTokens(); !ok {
		v := gatewayapikey.DefaultQuotaTotalTokens
		_c.mutation.SetQuotaTotalTokens(v)
	}
	if _, ok := _c.mutation.QuotaDailyTokens(); !ok {
		v := gatewayapikey.DefaultQuotaDailyTokens
		_c.mutation.SetQuotaDailyTokens(v)
	}
	if _, ok := _c.mutation.QuotaWeeklyTokens(); !ok {
		v := gatewayapikey.DefaultQuotaWeeklyTokens
		_c.mutation.SetQuotaWeeklyTokens(v)
	}
	if _, ok := _c.mutation.QuotaDailyInputTokens(); !ok {
		v := gatewayapikey.DefaultQuotaDailyInputTokens
		_c.mutation.SetQuotaDailyInputTokens(v)
	}
	if _, ok := _c.mutation.QuotaWeeklyInputTokens(); !ok {
		v := gatewayapikey.DefaultQuotaWeeklyInputTokens
		_c.mutation.SetQuotaWeeklyInputTokens(v)
	}
	if _, ok := _c.mutation.QuotaDailyOutputTokens(); !ok {
		v := gatewayapikey.DefaultQuotaDailyOutputTokens
		_c.mutation.SetQuotaDailyOutputTokens(v)
	}
	if _, ok := _c.mutation.QuotaWeeklyOutputTokens(); !ok {
		v := gatewayapikey.DefaultQuotaWeeklyOutputTokens
		_c.mutation.SetQuotaWeeklyOutputTokens(v)
	}
	if _, ok := _c.mutation.QuotaDailyBillableInputTokens(); !ok {
		v := gatewayapikey.DefaultQuotaDailyBillableInputTokens
		_c.mutation.SetQuotaDailyBillableInputTokens(v)
	}
	if _, ok := _c.mutation.QuotaWeeklyBillableInputTokens(); !ok {
		v := gatewayapikey.DefaultQuotaWeeklyBillableInputTokens
		_c.mutation.SetQuotaWeeklyBillableInputTokens(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gatewayapikey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gatewayapikey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GatewayAPIKeyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "GatewayAPIKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := gatewayapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GatewayAPIKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "GatewayAPIKey.key_hash"`)}
	}
	if v, ok := _c.mutation.KeyHash(); ok {
		if err := gatewayapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "GatewayAPIKey.key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlainKey(); !ok {
		return &ValidationError{Name: "plain_key", err: errors.New(`ent: missing required field "GatewayAPIKey.plain_key"`)}
	}
	if v, ok := _c.mutation.PlainKey(); ok {
		if err := gatewayapikey.PlainKeyValidator(v); err != nil {
			return &ValidationError{Name: "plain_key", err: fmt.Errorf(`ent: validator failed for field "GatewayAPIKey.plain_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyPrefix(); !ok {
		return &ValidationError{Name: "key_prefix", err: errors.New(`ent: missing required field "GatewayAPIKey.key_prefix"`)}
	}
	if v, ok := _c.mutation.KeyPrefix(); ok {
		if err := gatewayapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "GatewayAPIKey.key_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyLast4(); !ok {
		return &ValidationError{Name: "key_last4", err: errors.New(`ent: missing required field "GatewayAPIKey.key_last4"`)}
	}
	if v, ok := _c.mutation.KeyLast4(); ok {
		if err := gatewayapikey.KeyLast4Validator(v); err != nil {
			return &ValidationError{Name: "key_last4", err: fmt.Errorf(`ent: validator failed for field "GatewayAPIKey.key_last4": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "GatewayAPIKey.disabled"`)}
	}
	if _, ok := _c.mutation.QuotaRequests(); !ok {
		return &ValidationError{Name: "quota_requests", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_requests"`)}
	}
	if _, ok := _c.mutation.QuotaTotalTokens(); !ok {
		return &ValidationError{Name: "quota_total_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_total_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaDailyTokens(); !ok {
		return &ValidationError{Name: "quota_daily_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_daily_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaWeeklyTokens(); !ok {
		return &ValidationError{Name: "quota_weekly_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_weekly_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaDailyInputTokens(); !ok {
		return &ValidationError{Name: "quota_daily_input_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_daily_input_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaWeeklyInputTokens(); !ok {
		return &ValidationError{Name: "quota_weekly_input_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_weekly_input_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaDailyOutputTokens(); !ok {
		return &ValidationError{Name: "quota_daily_output_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_daily_output_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaWeeklyOutputTokens(); !ok {
		return &ValidationError{Name: "quota_weekly_output_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_weekly_output_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaDailyBillableInputTokens(); !ok {
		return &ValidationError{Name: "quota_daily_billable_input_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_daily_billable_input_tokens"`)}
	}
	if _, ok := _c.mutation.QuotaWeeklyBillableInputTokens(); !ok {
		return &ValidationError{Name: "quota_weekly_billable_input_tokens", err: errors.New(`ent: missing required field "GatewayAPIKey.quota_weekly_billable_input_tokens"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GatewayAPIKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GatewayAPIKey.updated_at"`)}
	}
	return nil
}

func (_c *GatewayAPIKeyCreate) sqlSave(ctx context.Context) (*GatewayAPIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GatewayAPIKeyCreate) createSpec() (*GatewayAPIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &GatewayAPIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gatewayapikey.Table, sqlgraph.NewFieldSpec(gatewayapikey.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OwnerUserID(); ok {
		_spec.SetField(gatewayapikey.FieldOwnerUserID, field.TypeInt, value)
		_node.OwnerUserID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(gatewayapikey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(gatewayapikey.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.PlainKey(); ok {
		_spec.SetField(gatewayapikey.FieldPlainKey, field.TypeString, value)
		_node.PlainKey = value
	}
	if value, ok := _c.mutation.KeyPrefix(); ok {
		_spec.SetField(gatewayapikey.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := _c.mutation.KeyLast4(); ok {
		_spec.SetField(gatewayapikey.FieldKeyLast4, field.TypeString, value)
		_node.KeyLast4 = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(gatewayapikey.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.QuotaRequests(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaRequests, field.TypeInt64, value)
		_node.QuotaRequests = value
	}
	if value, ok := _c.mutation.QuotaTotalTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaTotalTokens, field.TypeInt64, value)
		_node.QuotaTotalTokens = value
	}
	if value, ok := _c.mutation.QuotaDailyTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaDailyTokens, field.TypeInt64, value)
		_node.QuotaDailyTokens = value
	}
	if value, ok := _c.mutation.QuotaWeeklyTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaWeeklyTokens, field.TypeInt64, value)
		_node.QuotaWeeklyTokens = value
	}
	if value, ok := _c.mutation.QuotaDailyInputTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaDailyInputTokens, field.TypeInt64, value)
		_node.QuotaDailyInputTokens = value
	}
	if value, ok := _c.mutation.QuotaWeeklyInputTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaWeeklyInputTokens, field.TypeInt64, value)
		_node.QuotaWeeklyInputTokens = value
	}
	if value, ok := _c.mutation.QuotaDailyOutputTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaDailyOutputTokens, field.TypeInt64, value)
		_node.QuotaDailyOutputTokens = value
	}
	if value, ok := _c.mutation.QuotaWeeklyOutputTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaWeeklyOutputTokens, field.TypeInt64, value)
		_node.QuotaWeeklyOutputTokens = value
	}
	if value, ok := _c.mutation.QuotaDailyBillableInputTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaDailyBillableInputTokens, field.TypeInt64, value)
		_node.QuotaDailyBillableInputTokens = value
	}
	if value, ok := _c.mutation.QuotaWeeklyBillableInputTokens(); ok {
		_spec.SetField(gatewayapikey.FieldQuotaWeeklyBillableInputTokens, field.TypeInt64, value)
		_node.QuotaWeeklyBillableInputTokens = value
	}
	if value, ok := _c.mutation.AllowedModels(); ok {
		_spec.SetField(gatewayapikey.FieldAllowedModels, field.TypeJSON, value)
		_node.AllowedModels = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(gatewayapikey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gatewayapikey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gatewayapikey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GatewayAPIKeyCreateBulk is the builder for creating many GatewayAPIKey entities in bulk.
type GatewayAPIKeyCreateBulk struct {
	config
	err      error
	builders []*GatewayAPIKeyCreate
}

// Save creates the GatewayAPIKey entities in the database.
func (_c *GatewayAPIKeyCreateBulk) Save(ctx context.Context) ([]*GatewayAPIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GatewayAPIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GatewayAPIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GatewayAPIKeyCreateBulk) SaveX(ctx context.Context) []*GatewayAPIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GatewayAPIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GatewayAPIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
