// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/internal/data/model/ent/adminuser"
	"server/internal/data/model/ent/gatewayalertevent"
	"server/internal/data/model/ent/gatewayalertrule"
	"server/internal/data/model/ent/gatewayapikey"
	"server/internal/data/model/ent/gatewayauditlog"
	"server/internal/data/model/ent/gatewaymodel"
	"server/internal/data/model/ent/gatewaymodelprice"
	"server/internal/data/model/ent/gatewaypolicy"
	"server/internal/data/model/ent/gatewaysetting"
	"server/internal/data/model/ent/gatewayusagelog"
	"server/internal/data/model/ent/user"
	"server/internal/data/model/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescUsername is the schema descriptor for username field.
	adminuserDescUsername := adminuserFields[0].Descriptor()
	// adminuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	adminuser.UsernameValidator = func() func(string) error {
		validators := adminuserDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminuserDescPasswordHash is the schema descriptor for password_hash field.
	adminuserDescPasswordHash := adminuserFields[1].Descriptor()
	// adminuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	adminuser.PasswordHashValidator = adminuserDescPasswordHash.Validators[0].(func(string) error)
	// adminuserDescOauthProvider is the schema descriptor for oauth_provider field.
	adminuserDescOauthProvider := adminuserFields[2].Descriptor()
	// adminuser.OauthProviderValidator is a validator for the "oauth_provider" field. It is called by the builders before save.
	adminuser.OauthProviderValidator = adminuserDescOauthProvider.Validators[0].(func(string) error)
	// adminuserDescOauthSubject is the schema descriptor for oauth_subject field.
	adminuserDescOauthSubject := adminuserFields[3].Descriptor()
	// adminuser.OauthSubjectValidator is a validator for the "oauth_subject" field. It is called by the builders before save.
	adminuser.OauthSubjectValidator = adminuserDescOauthSubject.Validators[0].(func(string) error)
	// adminuserDescOauthEmail is the schema descriptor for oauth_email field.
	adminuserDescOauthEmail := adminuserFields[4].Descriptor()
	// adminuser.OauthEmailValidator is a validator for the "oauth_email" field. It is called by the builders before save.
	adminuser.OauthEmailValidator = adminuserDescOauthEmail.Validators[0].(func(string) error)
	// adminuserDescOauthDisplayName is the schema descriptor for oauth_display_name field.
	adminuserDescOauthDisplayName := adminuserFields[5].Descriptor()
	// adminuser.OauthDisplayNameValidator is a validator for the "oauth_display_name" field. It is called by the builders before save.
	adminuser.OauthDisplayNameValidator = adminuserDescOauthDisplayName.Validators[0].(func(string) error)
	// adminuserDescDisabled is the schema descriptor for disabled field.
	adminuserDescDisabled := adminuserFields[6].Descriptor()
	// adminuser.DefaultDisabled holds the default value on creation for the disabled field.
	adminuser.DefaultDisabled = adminuserDescDisabled.Default.(bool)
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserFields[8].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserFields[9].Descriptor()
	// adminuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminuser.DefaultUpdatedAt = adminuserDescUpdatedAt.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewayapikeyFields := schema.GatewayAPIKey{}.Fields()
	_ = gatewayapikeyFields
	// gatewayapikeyDescName is the schema descriptor for name field.
	gatewayapikeyDescName := gatewayapikeyFields[1].Descriptor()
	// gatewayapikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gatewayapikey.NameValidator = func() func(string) error {
		validators := gatewayapikeyDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayapikeyDescKeyHash is the schema descriptor for key_hash field.
	gatewayapikeyDescKeyHash := gatewayapikeyFields[2].Descriptor()
	// gatewayapikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	gatewayapikey.KeyHashValidator = func() func(string) error {
		validators := gatewayapikeyDescKeyHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key_hash string) error {
			for _, fn := range fns {
				if err := fn(key_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayapikeyDescPlainKey is the schema descriptor for plain_key field.
	gatewayapikeyDescPlainKey := gatewayapikeyFields[3].Descriptor()
	// gatewayapikey.DefaultPlainKey holds the default value on creation for the plain_key field.
	gatewayapikey.DefaultPlainKey = gatewayapikeyDescPlainKey.Default.(string)
	// gatewayapikey.PlainKeyValidator is a validator for the "plain_key" field. It is called by the builders before save.
	gatewayapikey.PlainKeyValidator = gatewayapikeyDescPlainKey.Validators[0].(func(string) error)
	// gatewayapikeyDescKeyPrefix is the schema descriptor for key_prefix field.
	gatewayapikeyDescKeyPrefix := gatewayapikeyFields[4].Descriptor()
	// gatewayapikey.KeyPrefixValidator is a validator for the "key_prefix" field. It is called by the builders before save.
	gatewayapikey.KeyPrefixValidator = func() func(string) error {
		validators := gatewayapikeyDescKeyPrefix.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key_prefix string) error {
			for _, fn := range fns {
				if err := fn(key_prefix); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayapikeyDescKeyLast4 is the schema descriptor for key_last4 field.
	gatewayapikeyDescKeyLast4 := gatewayapikeyFields[5].Descriptor()
	// gatewayapikey.KeyLast4Validator is a validator for the "key_last4" field. It is called by the builders before save.
	gatewayapikey.KeyLast4Validator = func() func(string) error {
		validators := gatewayapikeyDescKeyLast4.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key_last4 string) error {
			for _, fn := range fns {
				if err := fn(key_last4); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayapikeyDescDisabled is the schema descriptor for disabled field.
	gatewayapikeyDescDisabled := gatewayapikeyFields[6].Descriptor()
	// gatewayapikey.DefaultDisabled holds the default value on creation for the disabled field.
	gatewayapikey.DefaultDisabled = gatewayapikeyDescDisabled.Default.(bool)
	// gatewayapikeyDescQuotaRequests is the schema descriptor for quota_requests field.
	gatewayapikeyDescQuotaRequests := gatewayapikeyFields[7].Descriptor()
	// gatewayapikey.DefaultQuotaRequests holds the default value on creation for the quota_requests field.
	gatewayapikey.DefaultQuotaRequests = gatewayapikeyDescQuotaRequests.Default.(int64)
	// gatewayapikeyDescQuotaTotalTokens is the schema descriptor for quota_total_tokens field.
	gatewayapikeyDescQuotaTotalTokens := gatewayapikeyFields[8].Descriptor()
	// gatewayapikey.DefaultQuotaTotalTokens holds the default value on creation for the quota_total_tokens field.
	gatewayapikey.DefaultQuotaTotalTokens = gatewayapikeyDescQuotaTotalTokens.Default.(int64)
	// gatewayapikeyDescQuotaDailyTokens is the schema descriptor for quota_daily_tokens field.
	gatewayapikeyDescQuotaDailyTokens := gatewayapikeyFields[9].Descriptor()
	// gatewayapikey.DefaultQuotaDailyTokens holds the default value on creation for the quota_daily_tokens field.
	gatewayapikey.DefaultQuotaDailyTokens = gatewayapikeyDescQuotaDailyTokens.Default.(int64)
	// gatewayapikeyDescQuotaWeeklyTokens is the schema descriptor for quota_weekly_tokens field.
	gatewayapikeyDescQuotaWeeklyTokens := gatewayapikeyFields[10].Descriptor()
	// gatewayapikey.DefaultQuotaWeeklyTokens holds the default value on creation for the quota_weekly_tokens field.
	gatewayapikey.DefaultQuotaWeeklyTokens = gatewayapikeyDescQuotaWeeklyTokens.Default.(int64)
	// gatewayapikeyDescQuotaDailyInputTokens is the schema descriptor for quota_daily_input_tokens field.
	gatewayapikeyDescQuotaDailyInputTokens := gatewayapikeyFields[11].Descriptor()
	// gatewayapikey.DefaultQuotaDailyInputTokens holds the default value on creation for the quota_daily_input_tokens field.
	gatewayapikey.DefaultQuotaDailyInputTokens = gatewayapikeyDescQuotaDailyInputTokens.Default.(int64)
	// gatewayapikeyDescQuotaWeeklyInputTokens is the schema descriptor for quota_weekly_input_tokens field.
	gatewayapikeyDescQuotaWeeklyInputTokens := gatewayapikeyFields[12].Descriptor()
	// gatewayapikey.DefaultQuotaWeeklyInputTokens holds the default value on creation for the quota_weekly_input_tokens field.
	gatewayapikey.DefaultQuotaWeeklyInputTokens = gatewayapikeyDescQuotaWeeklyInputTokens.Default.(int64)
	// gatewayapikeyDescQuotaDailyOutputTokens is the schema descriptor for quota_daily_output_tokens field.
	gatewayapikeyDescQuotaDailyOutputTokens := gatewayapikeyFields[13].Descriptor()
	// gatewayapikey.DefaultQuotaDailyOutputTokens holds the default value on creation for the quota_daily_output_tokens field.
	gatewayapikey.DefaultQuotaDailyOutputTokens = gatewayapikeyDescQuotaDailyOutputTokens.Default.(int64)
	// gatewayapikeyDescQuotaWeeklyOutputTokens is the schema descriptor for quota_weekly_output_tokens field.
	gatewayapikeyDescQuotaWeeklyOutputTokens := gatewayapikeyFields[14].Descriptor()
	// gatewayapikey.DefaultQuotaWeeklyOutputTokens holds the default value on creation for the quota_weekly_output_tokens field.
	gatewayapikey.DefaultQuotaWeeklyOutputTokens = gatewayapikeyDescQuotaWeeklyOutputTokens.Default.(int64)
	// gatewayapikeyDescQuotaDailyBillableInputTokens is the schema descriptor for quota_daily_billable_input_tokens field.
	gatewayapikeyDescQuotaDailyBillableInputTokens := gatewayapikeyFields[15].Descriptor()
	// gatewayapikey.DefaultQuotaDailyBillableInputTokens holds the default value on creation for the quota_daily_billable_input_tokens field.
	gatewayapikey.DefaultQuotaDailyBillableInputTokens = gatewayapikeyDescQuotaDailyBillableInputTokens.Default.(int64)
	// gatewayapikeyDescQuotaWeeklyBillableInputTokens is the schema descriptor for quota_weekly_billable_input_tokens field.
	gatewayapikeyDescQuotaWeeklyBillableInputTokens := gatewayapikeyFields[16].Descriptor()
	// gatewayapikey.DefaultQuotaWeeklyBillableInputTokens holds the default value on creation for the quota_weekly_billable_input_tokens field.
	gatewayapikey.DefaultQuotaWeeklyBillableInputTokens = gatewayapikeyDescQuotaWeeklyBillableInputTokens.Default.(int64)
	// gatewayapikeyDescCreatedAt is the schema descriptor for created_at field.
	gatewayapikeyDescCreatedAt := gatewayapikeyFields[19].Descriptor()
	// gatewayapikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewayapikey.DefaultCreatedAt = gatewayapikeyDescCreatedAt.Default.(func() time.Time)
	// gatewayapikeyDescUpdatedAt is the schema descriptor for updated_at field.
	gatewayapikeyDescUpdatedAt := gatewayapikeyFields[20].Descriptor()
	// gatewayapikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gatewayapikey.DefaultUpdatedAt = gatewayapikeyDescUpdatedAt.Default.(func() time.Time)
	// gatewayapikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gatewayapikey.UpdateDefaultUpdatedAt = gatewayapikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewayalerteventFields := schema.GatewayAlertEvent{}.Fields()
	_ = gatewayalerteventFields
	// gatewayalerteventDescRuleName is the schema descriptor for rule_name field.
	gatewayalerteventDescRuleName := gatewayalerteventFields[1].Descriptor()
	// gatewayalertevent.DefaultRuleName holds the default value on creation for the rule_name field.
	gatewayalertevent.DefaultRuleName = gatewayalerteventDescRuleName.Default.(string)
	// gatewayalertevent.RuleNameValidator is a validator for the "rule_name" field. It is called by the builders before save.
	gatewayalertevent.RuleNameValidator = gatewayalerteventDescRuleName.Validators[0].(func(string) error)
	// gatewayalerteventDescMetric is the schema descriptor for metric field.
	gatewayalerteventDescMetric := gatewayalerteventFields[2].Descriptor()
	// gatewayalertevent.MetricValidator is a validator for the "metric" field. It is called by the builders before save.
	gatewayalertevent.MetricValidator = func() func(string) error {
		validators := gatewayalerteventDescMetric.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(metric string) error {
			for _, fn := range fns {
				if err := fn(metric); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayalerteventDescValue is the schema descriptor for value field.
	gatewayalerteventDescValue := gatewayalerteventFields[3].Descriptor()
	// gatewayalertevent.DefaultValue holds the default value on creation for the value field.
	gatewayalertevent.DefaultValue = gatewayalerteventDescValue.Default.(float64)
	// gatewayalerteventDescThreshold is the schema descriptor for threshold field.
	gatewayalerteventDescThreshold := gatewayalerteventFields[4].Descriptor()
	// gatewayalertevent.DefaultThreshold holds the default value on creation for the threshold field.
	gatewayalertevent.DefaultThreshold = gatewayalerteventDescThreshold.Default.(float64)
	// gatewayalerteventDescStatus is the schema descriptor for status field.
	gatewayalerteventDescStatus := gatewayalerteventFields[5].Descriptor()
	// gatewayalertevent.DefaultStatus holds the default value on creation for the status field.
	gatewayalertevent.DefaultStatus = gatewayalerteventDescStatus.Default.(string)
	// gatewayalertevent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	gatewayalertevent.StatusValidator = gatewayalerteventDescStatus.Validators[0].(func(string) error)
	// gatewayalerteventDescCreatedAt is the schema descriptor for created_at field.
	gatewayalerteventDescCreatedAt := gatewayalerteventFields[8].Descriptor()
	// gatewayalertevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewayalertevent.DefaultCreatedAt = gatewayalerteventDescCreatedAt.Default.(func() time.Time)
	gatewayalertruleFields := schema.GatewayAlertRule{}.Fields()
	_ = gatewayalertruleFields
	// gatewayalertruleDescName is the schema descriptor for name field.
	gatewayalertruleDescName := gatewayalertruleFields[0].Descriptor()
	// gatewayalertrule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	gatewayalertrule.NameValidator = func() func(string) error {
		validators := gatewayalertruleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayalertruleDescMetric is the schema descriptor for metric field.
	gatewayalertruleDescMetric := gatewayalertruleFields[1].Descriptor()
	// gatewayalertrule.MetricValidator is a validator for the "metric" field. It is called by the builders before save.
	gatewayalertrule.MetricValidator = func() func(string) error {
		validators := gatewayalertruleDescMetric.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(metric string) error {
			for _, fn := range fns {
				if err := fn(metric); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayalertruleDescOperator is the schema descriptor for operator field.
	gatewayalertruleDescOperator := gatewayalertruleFields[2].Descriptor()
	// gatewayalertrule.DefaultOperator holds the default value on creation for the operator field.
	gatewayalertrule.DefaultOperator = gatewayalertruleDescOperator.Default.(string)
	// gatewayalertrule.OperatorValidator is a validator for the "operator" field. It is called by the builders before save.
	gatewayalertrule.OperatorValidator = gatewayalertruleDescOperator.Validators[0].(func(string) error)
	// gatewayalertruleDescThreshold is the schema descriptor for threshold field.
	gatewayalertruleDescThreshold := gatewayalertruleFields[3].Descriptor()
	// gatewayalertrule.DefaultThreshold holds the default value on creation for the threshold field.
	gatewayalertrule.DefaultThreshold = gatewayalertruleDescThreshold.Default.(float64)
	// gatewayalertruleDescWindowSeconds is the schema descriptor for window_seconds field.
	gatewayalertruleDescWindowSeconds := gatewayalertruleFields[4].Descriptor()
	// gatewayalertrule.DefaultWindowSeconds holds the default value on creation for the window_seconds field.
	gatewayalertrule.DefaultWindowSeconds = gatewayalertruleDescWindowSeconds.Default.(int64)
	// gatewayalertruleDescEnabled is the schema descriptor for enabled field.
	gatewayalertruleDescEnabled := gatewayalertruleFields[5].Descriptor()
	// gatewayalertrule.DefaultEnabled holds the default value on creation for the enabled field.
	gatewayalertrule.DefaultEnabled = gatewayalertruleDescEnabled.Default.(bool)
	// gatewayalertruleDescCreatedAt is the schema descriptor for created_at field.
	gatewayalertruleDescCreatedAt := gatewayalertruleFields[6].Descriptor()
	// gatewayalertrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewayalertrule.DefaultCreatedAt = gatewayalertruleDescCreatedAt.Default.(func() time.Time)
	// gatewayalertruleDescUpdatedAt is the schema descriptor for updated_at field.
	gatewayalertruleDescUpdatedAt := gatewayalertruleFields[7].Descriptor()
	// gatewayalertrule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gatewayalertrule.DefaultUpdatedAt = gatewayalertruleDescUpdatedAt.Default.(func() time.Time)
	// gatewayalertrule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gatewayalertrule.UpdateDefaultUpdatedAt = gatewayalertruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewayauditlogFields := schema.GatewayAuditLog{}.Fields()
	_ = gatewayauditlogFields
	// gatewayauditlogDescActorID is the schema descriptor for actor_id field.
	gatewayauditlogDescActorID := gatewayauditlogFields[0].Descriptor()
	// gatewayauditlog.DefaultActorID holds the default value on creation for the actor_id field.
	gatewayauditlog.DefaultActorID = gatewayauditlogDescActorID.Default.(int)
	// gatewayauditlogDescActorName is the schema descriptor for actor_name field.
	gatewayauditlogDescActorName := gatewayauditlogFields[1].Descriptor()
	// gatewayauditlog.DefaultActorName holds the default value on creation for the actor_name field.
	gatewayauditlog.DefaultActorName = gatewayauditlogDescActorName.Default.(string)
	// gatewayauditlog.ActorNameValidator is a validator for the "actor_name" field. It is called by the builders before save.
	gatewayauditlog.ActorNameValidator = gatewayauditlogDescActorName.Validators[0].(func(string) error)
	// gatewayauditlogDescActorRole is the schema descriptor for actor_role field.
	gatewayauditlogDescActorRole := gatewayauditlogFields[2].Descriptor()
	// gatewayauditlog.DefaultActorRole holds the default value on creation for the actor_role field.
	gatewayauditlog.DefaultActorRole = gatewayauditlogDescActorRole.Default.(string)
	// gatewayauditlog.ActorRoleValidator is a validator for the "actor_role" field. It is called by the builders before save.
	gatewayauditlog.ActorRoleValidator = gatewayauditlogDescActorRole.Validators[0].(func(string) error)
	// gatewayauditlogDescAction is the schema descriptor for action field.
	gatewayauditlogDescAction := gatewayauditlogFields[3].Descriptor()
	// gatewayauditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	gatewayauditlog.ActionValidator = func() func(string) error {
		validators := gatewayauditlogDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayauditlogDescTargetType is the schema descriptor for target_type field.
	gatewayauditlogDescTargetType := gatewayauditlogFields[4].Descriptor()
	// gatewayauditlog.DefaultTargetType holds the default value on creation for the target_type field.
	gatewayauditlog.DefaultTargetType = gatewayauditlogDescTargetType.Default.(string)
	// gatewayauditlog.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	gatewayauditlog.TargetTypeValidator = gatewayauditlogDescTargetType.Validators[0].(func(string) error)
	// gatewayauditlogDescTargetID is the schema descriptor for target_id field.
	gatewayauditlogDescTargetID := gatewayauditlogFields[5].Descriptor()
	// gatewayauditlog.DefaultTargetID holds the default value on creation for the target_id field.
	gatewayauditlog.DefaultTargetID = gatewayauditlogDescTargetID.Default.(string)
	// gatewayauditlog.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	gatewayauditlog.TargetIDValidator = gatewayauditlogDescTargetID.Validators[0].(func(string) error)
	// gatewayauditlogDescCreatedAt is the schema descriptor for created_at field.
	gatewayauditlogDescCreatedAt := gatewayauditlogFields[7].Descriptor()
	// gatewayauditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewayauditlog.DefaultCreatedAt = gatewayauditlogDescCreatedAt.Default.(func() time.Time)
	gatewaymodelFields := schema.GatewayModel{}.Fields()
	_ = gatewaymodelFields
	// gatewaymodelDescModelID is the schema descriptor for model_id field.
	gatewaymodelDescModelID := gatewaymodelFields[0].Descriptor()
	// gatewaymodel.ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	gatewaymodel.ModelIDValidator = func() func(string) error {
		validators := gatewaymodelDescModelID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model_id string) error {
			for _, fn := range fns {
				if err := fn(model_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewaymodelDescOwnedBy is the schema descriptor for owned_by field.
	gatewaymodelDescOwnedBy := gatewaymodelFields[1].Descriptor()
	// gatewaymodel.DefaultOwnedBy holds the default value on creation for the owned_by field.
	gatewaymodel.DefaultOwnedBy = gatewaymodelDescOwnedBy.Default.(string)
	// gatewaymodel.OwnedByValidator is a validator for the "owned_by" field. It is called by the builders before save.
	gatewaymodel.OwnedByValidator = gatewaymodelDescOwnedBy.Validators[0].(func(string) error)
	// gatewaymodelDescCreatedUnix is the schema descriptor for created_unix field.
	gatewaymodelDescCreatedUnix := gatewaymodelFields[2].Descriptor()
	// gatewaymodel.DefaultCreatedUnix holds the default value on creation for the created_unix field.
	gatewaymodel.DefaultCreatedUnix = gatewaymodelDescCreatedUnix.Default.(int64)
	// gatewaymodelDescEnabled is the schema descriptor for enabled field.
	gatewaymodelDescEnabled := gatewaymodelFields[3].Descriptor()
	// gatewaymodel.DefaultEnabled holds the default value on creation for the enabled field.
	gatewaymodel.DefaultEnabled = gatewaymodelDescEnabled.Default.(bool)
	// gatewaymodelDescSource is the schema descriptor for source field.
	gatewaymodelDescSource := gatewaymodelFields[4].Descriptor()
	// gatewaymodel.DefaultSource holds the default value on creation for the source field.
	gatewaymodel.DefaultSource = gatewaymodelDescSource.Default.(string)
	// gatewaymodel.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	gatewaymodel.SourceValidator = gatewaymodelDescSource.Validators[0].(func(string) error)
	// gatewaymodelDescCreatedAt is the schema descriptor for created_at field.
	gatewaymodelDescCreatedAt := gatewaymodelFields[6].Descriptor()
	// gatewaymodel.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewaymodel.DefaultCreatedAt = gatewaymodelDescCreatedAt.Default.(func() time.Time)
	// gatewaymodelDescUpdatedAt is the schema descriptor for updated_at field.
	gatewaymodelDescUpdatedAt := gatewaymodelFields[7].Descriptor()
	// gatewaymodel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gatewaymodel.DefaultUpdatedAt = gatewaymodelDescUpdatedAt.Default.(func() time.Time)
	// gatewaymodel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gatewaymodel.UpdateDefaultUpdatedAt = gatewaymodelDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewaymodelpriceFields := schema.GatewayModelPrice{}.Fields()
	_ = gatewaymodelpriceFields
	// gatewaymodelpriceDescModelID is the schema descriptor for model_id field.
	gatewaymodelpriceDescModelID := gatewaymodelpriceFields[0].Descriptor()
	// gatewaymodelprice.ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	gatewaymodelprice.ModelIDValidator = func() func(string) error {
		validators := gatewaymodelpriceDescModelID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model_id string) error {
			for _, fn := range fns {
				if err := fn(model_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewaymodelpriceDescInputUsdPerMillion is the schema descriptor for input_usd_per_million field.
	gatewaymodelpriceDescInputUsdPerMillion := gatewaymodelpriceFields[1].Descriptor()
	// gatewaymodelprice.DefaultInputUsdPerMillion holds the default value on creation for the input_usd_per_million field.
	gatewaymodelprice.DefaultInputUsdPerMillion = gatewaymodelpriceDescInputUsdPerMillion.Default.(float64)
	// gatewaymodelpriceDescCachedInputUsdPerMillion is the schema descriptor for cached_input_usd_per_million field.
	gatewaymodelpriceDescCachedInputUsdPerMillion := gatewaymodelpriceFields[2].Descriptor()
	// gatewaymodelprice.DefaultCachedInputUsdPerMillion holds the default value on creation for the cached_input_usd_per_million field.
	gatewaymodelprice.DefaultCachedInputUsdPerMillion = gatewaymodelpriceDescCachedInputUsdPerMillion.Default.(float64)
	// gatewaymodelpriceDescOutputUsdPerMillion is the schema descriptor for output_usd_per_million field.
	gatewaymodelpriceDescOutputUsdPerMillion := gatewaymodelpriceFields[3].Descriptor()
	// gatewaymodelprice.DefaultOutputUsdPerMillion holds the default value on creation for the output_usd_per_million field.
	gatewaymodelprice.DefaultOutputUsdPerMillion = gatewaymodelpriceDescOutputUsdPerMillion.Default.(float64)
	// gatewaymodelpriceDescCreatedAt is the schema descriptor for created_at field.
	gatewaymodelpriceDescCreatedAt := gatewaymodelpriceFields[4].Descriptor()
	// gatewaymodelprice.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewaymodelprice.DefaultCreatedAt = gatewaymodelpriceDescCreatedAt.Default.(func() time.Time)
	// gatewaymodelpriceDescUpdatedAt is the schema descriptor for updated_at field.
	gatewaymodelpriceDescUpdatedAt := gatewaymodelpriceFields[5].Descriptor()
	// gatewaymodelprice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gatewaymodelprice.DefaultUpdatedAt = gatewaymodelpriceDescUpdatedAt.Default.(func() time.Time)
	// gatewaymodelprice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gatewaymodelprice.UpdateDefaultUpdatedAt = gatewaymodelpriceDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewaypolicyFields := schema.GatewayPolicy{}.Fields()
	_ = gatewaypolicyFields
	// gatewaypolicyDescAPIKeyID is the schema descriptor for api_key_id field.
	gatewaypolicyDescAPIKeyID := gatewaypolicyFields[0].Descriptor()
	// gatewaypolicy.APIKeyIDValidator is a validator for the "api_key_id" field. It is called by the builders before save.
	gatewaypolicy.APIKeyIDValidator = gatewaypolicyDescAPIKeyID.Validators[0].(func(int) error)
	// gatewaypolicyDescModelID is the schema descriptor for model_id field.
	gatewaypolicyDescModelID := gatewaypolicyFields[1].Descriptor()
	// gatewaypolicy.ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	gatewaypolicy.ModelIDValidator = func() func(string) error {
		validators := gatewaypolicyDescModelID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model_id string) error {
			for _, fn := range fns {
				if err := fn(model_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewaypolicyDescRpm is the schema descriptor for rpm field.
	gatewaypolicyDescRpm := gatewaypolicyFields[2].Descriptor()
	// gatewaypolicy.DefaultRpm holds the default value on creation for the rpm field.
	gatewaypolicy.DefaultRpm = gatewaypolicyDescRpm.Default.(int64)
	// gatewaypolicyDescTpm is the schema descriptor for tpm field.
	gatewaypolicyDescTpm := gatewaypolicyFields[3].Descriptor()
	// gatewaypolicy.DefaultTpm holds the default value on creation for the tpm field.
	gatewaypolicy.DefaultTpm = gatewaypolicyDescTpm.Default.(int64)
	// gatewaypolicyDescDailyRequests is the schema descriptor for daily_requests field.
	gatewaypolicyDescDailyRequests := gatewaypolicyFields[4].Descriptor()
	// gatewaypolicy.DefaultDailyRequests holds the default value on creation for the daily_requests field.
	gatewaypolicy.DefaultDailyRequests = gatewaypolicyDescDailyRequests.Default.(int64)
	// gatewaypolicyDescMonthlyRequests is the schema descriptor for monthly_requests field.
	gatewaypolicyDescMonthlyRequests := gatewaypolicyFields[5].Descriptor()
	// gatewaypolicy.DefaultMonthlyRequests holds the default value on creation for the monthly_requests field.
	gatewaypolicy.DefaultMonthlyRequests = gatewaypolicyDescMonthlyRequests.Default.(int64)
	// gatewaypolicyDescDailyTokens is the schema descriptor for daily_tokens field.
	gatewaypolicyDescDailyTokens := gatewaypolicyFields[6].Descriptor()
	// gatewaypolicy.DefaultDailyTokens holds the default value on creation for the daily_tokens field.
	gatewaypolicy.DefaultDailyTokens = gatewaypolicyDescDailyTokens.Default.(int64)
	// gatewaypolicyDescMonthlyTokens is the schema descriptor for monthly_tokens field.
	gatewaypolicyDescMonthlyTokens := gatewaypolicyFields[7].Descriptor()
	// gatewaypolicy.DefaultMonthlyTokens holds the default value on creation for the monthly_tokens field.
	gatewaypolicy.DefaultMonthlyTokens = gatewaypolicyDescMonthlyTokens.Default.(int64)
	// gatewaypolicyDescCreatedAt is the schema descriptor for created_at field.
	gatewaypolicyDescCreatedAt := gatewaypolicyFields[8].Descriptor()
	// gatewaypolicy.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewaypolicy.DefaultCreatedAt = gatewaypolicyDescCreatedAt.Default.(func() time.Time)
	// gatewaypolicyDescUpdatedAt is the schema descriptor for updated_at field.
	gatewaypolicyDescUpdatedAt := gatewaypolicyFields[9].Descriptor()
	// gatewaypolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gatewaypolicy.DefaultUpdatedAt = gatewaypolicyDescUpdatedAt.Default.(func() time.Time)
	// gatewaypolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gatewaypolicy.UpdateDefaultUpdatedAt = gatewaypolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewaysettingFields := schema.GatewaySetting{}.Fields()
	_ = gatewaysettingFields
	// gatewaysettingDescKey is the schema descriptor for key field.
	gatewaysettingDescKey := gatewaysettingFields[0].Descriptor()
	// gatewaysetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	gatewaysetting.KeyValidator = func() func(string) error {
		validators := gatewaysettingDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewaysettingDescValue is the schema descriptor for value field.
	gatewaysettingDescValue := gatewaysettingFields[1].Descriptor()
	// gatewaysetting.DefaultValue holds the default value on creation for the value field.
	gatewaysetting.DefaultValue = gatewaysettingDescValue.Default.(string)
	// gatewaysetting.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	gatewaysetting.ValueValidator = gatewaysettingDescValue.Validators[0].(func(string) error)
	// gatewaysettingDescCreatedAt is the schema descriptor for created_at field.
	gatewaysettingDescCreatedAt := gatewaysettingFields[2].Descriptor()
	// gatewaysetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewaysetting.DefaultCreatedAt = gatewaysettingDescCreatedAt.Default.(func() time.Time)
	// gatewaysettingDescUpdatedAt is the schema descriptor for updated_at field.
	gatewaysettingDescUpdatedAt := gatewaysettingFields[3].Descriptor()
	// gatewaysetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gatewaysetting.DefaultUpdatedAt = gatewaysettingDescUpdatedAt.Default.(func() time.Time)
	// gatewaysetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gatewaysetting.UpdateDefaultUpdatedAt = gatewaysettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	gatewayusagelogFields := schema.GatewayUsageLog{}.Fields()
	_ = gatewayusagelogFields
	// gatewayusagelogDescAPIKeyPrefix is the schema descriptor for api_key_prefix field.
	gatewayusagelogDescAPIKeyPrefix := gatewayusagelogFields[1].Descriptor()
	// gatewayusagelog.DefaultAPIKeyPrefix holds the default value on creation for the api_key_prefix field.
	gatewayusagelog.DefaultAPIKeyPrefix = gatewayusagelogDescAPIKeyPrefix.Default.(string)
	// gatewayusagelog.APIKeyPrefixValidator is a validator for the "api_key_prefix" field. It is called by the builders before save.
	gatewayusagelog.APIKeyPrefixValidator = gatewayusagelogDescAPIKeyPrefix.Validators[0].(func(string) error)
	// gatewayusagelogDescSessionID is the schema descriptor for session_id field.
	gatewayusagelogDescSessionID := gatewayusagelogFields[2].Descriptor()
	// gatewayusagelog.DefaultSessionID holds the default value on creation for the session_id field.
	gatewayusagelog.DefaultSessionID = gatewayusagelogDescSessionID.Default.(string)
	// gatewayusagelog.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	gatewayusagelog.SessionIDValidator = gatewayusagelogDescSessionID.Validators[0].(func(string) error)
	// gatewayusagelogDescRequestID is the schema descriptor for request_id field.
	gatewayusagelogDescRequestID := gatewayusagelogFields[3].Descriptor()
	// gatewayusagelog.DefaultRequestID holds the default value on creation for the request_id field.
	gatewayusagelog.DefaultRequestID = gatewayusagelogDescRequestID.Default.(string)
	// gatewayusagelog.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	gatewayusagelog.RequestIDValidator = gatewayusagelogDescRequestID.Validators[0].(func(string) error)
	// gatewayusagelogDescMethod is the schema descriptor for method field.
	gatewayusagelogDescMethod := gatewayusagelogFields[4].Descriptor()
	// gatewayusagelog.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	gatewayusagelog.MethodValidator = func() func(string) error {
		validators := gatewayusagelogDescMethod.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(method string) error {
			for _, fn := range fns {
				if err := fn(method); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayusagelogDescPath is the schema descriptor for path field.
	gatewayusagelogDescPath := gatewayusagelogFields[5].Descriptor()
	// gatewayusagelog.PathValidator is a validator for the "path" field. It is called by the builders before save.
	gatewayusagelog.PathValidator = func() func(string) error {
		validators := gatewayusagelogDescPath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_path string) error {
			for _, fn := range fns {
				if err := fn(_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// gatewayusagelogDescEndpoint is the schema descriptor for endpoint field.
	gatewayusagelogDescEndpoint := gatewayusagelogFields[6].Descriptor()
	// gatewayusagelog.DefaultEndpoint holds the default value on creation for the endpoint field.
	gatewayusagelog.DefaultEndpoint = gatewayusagelogDescEndpoint.Default.(string)
	// gatewayusagelog.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	gatewayusagelog.EndpointValidator = gatewayusagelogDescEndpoint.Validators[0].(func(string) error)
	// gatewayusagelogDescModel is the schema descriptor for model field.
	gatewayusagelogDescModel := gatewayusagelogFields[7].Descriptor()
	// gatewayusagelog.DefaultModel holds the default value on creation for the model field.
	gatewayusagelog.DefaultModel = gatewayusagelogDescModel.Default.(string)
	// gatewayusagelog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	gatewayusagelog.ModelValidator = gatewayusagelogDescModel.Validators[0].(func(string) error)
	// gatewayusagelogDescReasoningEffort is the schema descriptor for reasoning_effort field.
	gatewayusagelogDescReasoningEffort := gatewayusagelogFields[8].Descriptor()
	// gatewayusagelog.DefaultReasoningEffort holds the default value on creation for the reasoning_effort field.
	gatewayusagelog.DefaultReasoningEffort = gatewayusagelogDescReasoningEffort.Default.(string)
	// gatewayusagelog.ReasoningEffortValidator is a validator for the "reasoning_effort" field. It is called by the builders before save.
	gatewayusagelog.ReasoningEffortValidator = gatewayusagelogDescReasoningEffort.Validators[0].(func(string) error)
	// gatewayusagelogDescStatusCode is the schema descriptor for status_code field.
	gatewayusagelogDescStatusCode := gatewayusagelogFields[9].Descriptor()
	// gatewayusagelog.DefaultStatusCode holds the default value on creation for the status_code field.
	gatewayusagelog.DefaultStatusCode = gatewayusagelogDescStatusCode.Default.(int)
	// gatewayusagelogDescSuccess is the schema descriptor for success field.
	gatewayusagelogDescSuccess := gatewayusagelogFields[10].Descriptor()
	// gatewayusagelog.DefaultSuccess holds the default value on creation for the success field.
	gatewayusagelog.DefaultSuccess = gatewayusagelogDescSuccess.Default.(bool)
	// gatewayusagelogDescStream is the schema descriptor for stream field.
	gatewayusagelogDescStream := gatewayusagelogFields[11].Descriptor()
	// gatewayusagelog.DefaultStream holds the default value on creation for the stream field.
	gatewayusagelog.DefaultStream = gatewayusagelogDescStream.Default.(bool)
	// gatewayusagelogDescInputTokens is the schema descriptor for input_tokens field.
	gatewayusagelogDescInputTokens := gatewayusagelogFields[12].Descriptor()
	// gatewayusagelog.DefaultInputTokens holds the default value on creation for the input_tokens field.
	gatewayusagelog.DefaultInputTokens = gatewayusagelogDescInputTokens.Default.(int64)
	// gatewayusagelogDescOutputTokens is the schema descriptor for output_tokens field.
	gatewayusagelogDescOutputTokens := gatewayusagelogFields[13].Descriptor()
	// gatewayusagelog.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	gatewayusagelog.DefaultOutputTokens = gatewayusagelogDescOutputTokens.Default.(int64)
	// gatewayusagelogDescTotalTokens is the schema descriptor for total_tokens field.
	gatewayusagelogDescTotalTokens := gatewayusagelogFields[14].Descriptor()
	// gatewayusagelog.DefaultTotalTokens holds the default value on creation for the total_tokens field.
	gatewayusagelog.DefaultTotalTokens = gatewayusagelogDescTotalTokens.Default.(int64)
	// gatewayusagelogDescCachedTokens is the schema descriptor for cached_tokens field.
	gatewayusagelogDescCachedTokens := gatewayusagelogFields[15].Descriptor()
	// gatewayusagelog.DefaultCachedTokens holds the default value on creation for the cached_tokens field.
	gatewayusagelog.DefaultCachedTokens = gatewayusagelogDescCachedTokens.Default.(int64)
	// gatewayusagelogDescReasoningTokens is the schema descriptor for reasoning_tokens field.
	gatewayusagelogDescReasoningTokens := gatewayusagelogFields[16].Descriptor()
	// gatewayusagelog.DefaultReasoningTokens holds the default value on creation for the reasoning_tokens field.
	gatewayusagelog.DefaultReasoningTokens = gatewayusagelogDescReasoningTokens.Default.(int64)
	// gatewayusagelogDescRequestBytes is the schema descriptor for request_bytes field.
	gatewayusagelogDescRequestBytes := gatewayusagelogFields[17].Descriptor()
	// gatewayusagelog.DefaultRequestBytes holds the default value on creation for the request_bytes field.
	gatewayusagelog.DefaultRequestBytes = gatewayusagelogDescRequestBytes.Default.(int64)
	// gatewayusagelogDescResponseBytes is the schema descriptor for response_bytes field.
	gatewayusagelogDescResponseBytes := gatewayusagelogFields[18].Descriptor()
	// gatewayusagelog.DefaultResponseBytes holds the default value on creation for the response_bytes field.
	gatewayusagelog.DefaultResponseBytes = gatewayusagelogDescResponseBytes.Default.(int64)
	// gatewayusagelogDescDurationMs is the schema descriptor for duration_ms field.
	gatewayusagelogDescDurationMs := gatewayusagelogFields[19].Descriptor()
	// gatewayusagelog.DefaultDurationMs holds the default value on creation for the duration_ms field.
	gatewayusagelog.DefaultDurationMs = gatewayusagelogDescDurationMs.Default.(int64)
	// gatewayusagelogDescUpstreamConfiguredMode is the schema descriptor for upstream_configured_mode field.
	gatewayusagelogDescUpstreamConfiguredMode := gatewayusagelogFields[20].Descriptor()
	// gatewayusagelog.DefaultUpstreamConfiguredMode holds the default value on creation for the upstream_configured_mode field.
	gatewayusagelog.DefaultUpstreamConfiguredMode = gatewayusagelogDescUpstreamConfiguredMode.Default.(string)
	// gatewayusagelog.UpstreamConfiguredModeValidator is a validator for the "upstream_configured_mode" field. It is called by the builders before save.
	gatewayusagelog.UpstreamConfiguredModeValidator = gatewayusagelogDescUpstreamConfiguredMode.Validators[0].(func(string) error)
	// gatewayusagelogDescUpstreamMode is the schema descriptor for upstream_mode field.
	gatewayusagelogDescUpstreamMode := gatewayusagelogFields[21].Descriptor()
	// gatewayusagelog.DefaultUpstreamMode holds the default value on creation for the upstream_mode field.
	gatewayusagelog.DefaultUpstreamMode = gatewayusagelogDescUpstreamMode.Default.(string)
	// gatewayusagelog.UpstreamModeValidator is a validator for the "upstream_mode" field. It is called by the builders before save.
	gatewayusagelog.UpstreamModeValidator = gatewayusagelogDescUpstreamMode.Validators[0].(func(string) error)
	// gatewayusagelogDescUpstreamFallback is the schema descriptor for upstream_fallback field.
	gatewayusagelogDescUpstreamFallback := gatewayusagelogFields[22].Descriptor()
	// gatewayusagelog.DefaultUpstreamFallback holds the default value on creation for the upstream_fallback field.
	gatewayusagelog.DefaultUpstreamFallback = gatewayusagelogDescUpstreamFallback.Default.(bool)
	// gatewayusagelogDescUpstreamErrorType is the schema descriptor for upstream_error_type field.
	gatewayusagelogDescUpstreamErrorType := gatewayusagelogFields[23].Descriptor()
	// gatewayusagelog.DefaultUpstreamErrorType holds the default value on creation for the upstream_error_type field.
	gatewayusagelog.DefaultUpstreamErrorType = gatewayusagelogDescUpstreamErrorType.Default.(string)
	// gatewayusagelog.UpstreamErrorTypeValidator is a validator for the "upstream_error_type" field. It is called by the builders before save.
	gatewayusagelog.UpstreamErrorTypeValidator = gatewayusagelogDescUpstreamErrorType.Validators[0].(func(string) error)
	// gatewayusagelogDescErrorType is the schema descriptor for error_type field.
	gatewayusagelogDescErrorType := gatewayusagelogFields[25].Descriptor()
	// gatewayusagelog.DefaultErrorType holds the default value on creation for the error_type field.
	gatewayusagelog.DefaultErrorType = gatewayusagelogDescErrorType.Default.(string)
	// gatewayusagelog.ErrorTypeValidator is a validator for the "error_type" field. It is called by the builders before save.
	gatewayusagelog.ErrorTypeValidator = gatewayusagelogDescErrorType.Validators[0].(func(string) error)
	// gatewayusagelogDescCreatedAt is the schema descriptor for created_at field.
	gatewayusagelogDescCreatedAt := gatewayusagelogFields[26].Descriptor()
	// gatewayusagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	gatewayusagelog.DefaultCreatedAt = gatewayusagelogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescOauthProvider is the schema descriptor for oauth_provider field.
	userDescOauthProvider := userFields[2].Descriptor()
	// user.OauthProviderValidator is a validator for the "oauth_provider" field. It is called by the builders before save.
	user.OauthProviderValidator = userDescOauthProvider.Validators[0].(func(string) error)
	// userDescOauthSubject is the schema descriptor for oauth_subject field.
	userDescOauthSubject := userFields[3].Descriptor()
	// user.OauthSubjectValidator is a validator for the "oauth_subject" field. It is called by the builders before save.
	user.OauthSubjectValidator = userDescOauthSubject.Validators[0].(func(string) error)
	// userDescOauthEmail is the schema descriptor for oauth_email field.
	userDescOauthEmail := userFields[4].Descriptor()
	// user.OauthEmailValidator is a validator for the "oauth_email" field. It is called by the builders before save.
	user.OauthEmailValidator = userDescOauthEmail.Validators[0].(func(string) error)
	// userDescOauthDisplayName is the schema descriptor for oauth_display_name field.
	userDescOauthDisplayName := userFields[5].Descriptor()
	// user.OauthDisplayNameValidator is a validator for the "oauth_display_name" field. It is called by the builders before save.
	user.OauthDisplayNameValidator = userDescOauthDisplayName.Validators[0].(func(string) error)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[6].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[9].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
